'use strict';
const assert=require('assert');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const ROOT=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,p))).digest('hex');
const SQL=read('supabase/migrations/supabase_v3350_ai_vault.sql');const POST=read('supabase/migrations/supabase_v3350_postdeploy_evidence.sql');const EDGE=read('supabase/functions/nexus-copywriter-v3200/index.ts');
// Concrete supplied credentials and the unscoped CJ token must not be versioned.
for(const needle of ['gsk_xD2Q','sk-or-v1-e9fe','cBln94ZB','sk-c3d572','hwIZyIXU']){assert.ok(!SQL.includes(needle));assert.ok(!EDGE.includes(needle));}
assert.match(SQL,/create table if not exists public\.nexus_v3350_ai_vault/i);assert.doesNotMatch(SQL,/create\s+unlogged\s+table[\s\S]*nexus_v3350_ai_vault/i);assert.match(SQL,/token_enc\s+bytea\s+not null/i);assert.doesNotMatch(SQL,/\btoken\s+text|\bapi_key\s+text/i);assert.match(SQL,/current_setting\('nexus\.v3350_ai_tokens_json'/i);assert.match(SQL,/extensions\.pgp_sym_encrypt\(/i);assert.match(SQL,/cipher-algo=aes256/i);assert.match(SQL,/extensions\.pgp_sym_decrypt\(/i);assert.match(SQL,/nexus_satellites_kms/i);
assert.match(SQL,/\('groq','Groq Cloud',1/);assert.match(SQL,/\('openrouter','OpenRouter',2/);assert.match(SQL,/\('mistral','Mistral AI',3/);assert.match(SQL,/\('deepseek','DeepSeek Core',4/);assert.match(SQL,/set local statement_timeout='2000ms'/);assert.match(SQL,/set local lock_timeout='1000ms'/);assert.match(SQL,/exception when others/i);assert.match(SQL,/Sintonizado em Análise/i);assert.match(SQL,/grant execute on function public\.nexus_v3350_ai_pool_status\(\) to service_role/i);
assert.match(SQL,/v3350_cj_token',false/);assert.match(SQL,/token_persisted',false/);assert.match(SQL,/cloudflare_pages_deployed',false/);assert.match(SQL,/compose_modified',false/);assert.match(SQL,/go_modified',false/);assert.match(SQL,/jobid=60[\s\S]*schedule='10 seconds'/i);assert.match(SQL,/capability='v3350_ai_edge_deployment'[\s\S]*supabase_edge_deployed/);assert.doesNotMatch(SQL,/cron\.schedule|cron\.unschedule/i);assert.doesNotMatch(SQL,/(?:insert\s+into|update|delete\s+from)\s+public\.ads\b/i);
assert.match(POST,/v3340_edge_deployment',true/);assert.match(POST,/v3350_ai_edge_deployment',true/);assert.match(POST,/runtime_selected_provider','groq'/);assert.match(POST,/runtime_failover_branch_exercised',false/);assert.match(POST,/deterministic_copy_remains_canonical',true/);assert.match(POST,/cj_token_persisted',false/);assert.match(POST,/cloudflare_pages_deployed',false/);assert.match(POST,/set local statement_timeout='2000ms'/);assert.match(POST,/set local lock_timeout='1000ms'/);assert.doesNotMatch(POST,/cron\.schedule|cron\.unschedule|(?:insert\s+into|update|delete\s+from)\s+public\.ads\b/i);
// v3755 keeps the historical encrypted four-provider vault intact, but the live
// broker allowlist is narrowed to Groq plus the currently verified free Liquid route.
for(const env of ['GROQ_API_KEY','OPENROUTER_API_KEY'])assert.ok(EDGE.includes(env),env);assert.match(EDGE,/NEXUS_V3350_AI_PREVIEW_SECRET/);assert.match(EDGE,/sameSecret\(suppliedInternalSecret, START_SECRET\)[\s\S]*sameSecret\(suppliedInternalSecret, AI_PREVIEW_SECRET\)/);assert.match(EDGE,/normalizedSentence\(text\) !== normalizedSentence\(expected\)/);assert.match(EDGE,/No free-form model claim is accepted/);assert.match(EDGE,/const PROVIDERS:[\s\S]*key: "groq"[\s\S]*key: "openrouter_liquid"/);assert.match(EDGE,/liquid\/lfm-2\.5-2\.6b:free/);assert.match(EDGE,/Promise\.allSettled\(calls\)/);assert.match(EDGE,/AbortSignal\.timeout\(8000\)/);assert.match(EDGE,/groq_result_preferred: true/);assert.match(EDGE,/cost_zero_guaranteed: false/);assert.match(EDGE,/deterministic_copy_remains_canonical: true/g);assert.match(EDGE,/state: "Sintonizado em Análise"/);assert.match(EDGE,/ai_pool_key_based: true/);assert.match(EDGE,/keyless_service: false/);assert.doesNotMatch(EDGE,/worker_threads|Response\.redirect/i);
assert.strictEqual(sha('api/ads/go.js'),'e77aab2895e8a194542866bf7c9e997a0fe37138638ce57125c8536009827716');assert.strictEqual(sha('edge/jetstream/compose.ts'),'d99ce7b5ca412102659f44d6d58f8f84f1b111f0f08865f208f13fd12cc730d0');
console.log('v3350 encrypted AI pool tests: PASS');
