#!/usr/bin/env node
'use strict';
const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');
const sha = p => crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, p))).digest('hex');
const SQL = read('supabase/migrations/supabase_v3360_metropolitan_expansion.sql');
const EDGE = read('supabase/functions/nexus-metropolitan-v3360/index.ts');
const CJ = read('scripts/cj-product-catalog-sync.js');
const GO_TEST = read('tests/go.test.js');
const EVIDENCE = JSON.parse(read('docs/evidencias/v3360-metropolitan-evidence.json'));
function embedded(tag) {
  const re = new RegExp(`\\$${tag}\\$([\\s\\S]*?)\\$${tag}\\$::jsonb`);
  const m = SQL.match(re); assert.ok(m, `missing ${tag} seed`); return JSON.parse(m[1]);
}
const cities = embedded('v3360_city');
const placements = embedded('v3360_cj');
assert.strictEqual(cities.length, 816);
assert.deepStrictEqual(Object.fromEntries([...new Set(cities.map(x => x.source_country_code))].sort().map(cc => [cc, cities.filter(x => x.source_country_code === cc).length])), { BR: 50, CN: 115, DE: 92, GB: 39, IN: 74, JP: 50, RU: 127, US: 269 });
assert.strictEqual(cities.filter(x => x.routing_eligible).length, 812);
assert.strictEqual(cities.filter(x => x.admin_required_for_disambiguation).length, 27);
assert.deepStrictEqual(cities.filter(x => !x.routing_eligible).map(x => x.destination_name).sort(), ['Changhai County', 'Novomoskovsky Administrative Okrug', 'Sevastopol', 'Simferopol'].sort());
assert.ok(cities.every(x => Number(x.geonames_id) > 0 && /^[a-f0-9]{64}$/.test(x.source_sha256)));
assert.ok(cities.some(x => x.destination_name === 'Anápolis' && x.admin_area === 'Goiás'));
assert.ok(cities.some(x => x.destination_name === 'Huanggang' && x.aliases.includes('Huanggan')));
assert.ok(cities.some(x => x.destination_name === 'Tóquio' && x.admin_area === 'Tokyo' && x.aliases.includes('東京')));
assert.ok(cities.some(x => x.destination_name === 'Hubballi-Dharwad' && x.aliases.includes('Hubli-Dharwad')));
assert.ok(cities.filter(x => ['Sevastopol', 'Simferopol'].includes(x.destination_name)).every(x => x.routing_country_code === 'UA'));
assert.strictEqual(placements.length, 87);
assert.ok(placements.every(x => x.account_status === 'Active' && x.relationship_status === 'joined' && x.terms_status === 'ACTIVE' && x.pid_generated_link && x.link_type === 'Text Link'));
assert.ok(!placements.some(x => Object.keys(x).some(k => /^(?:affiliate_url|click_url|tracking_url|property_pid|token)$/i.test(k))));
assert.match(SQL, /route_enabled boolean not null default false/i);
assert.match(SQL, /affiliate_url_enc bytea/i);
assert.match(SQL, /pgp_sym_encrypt\(v_url,v_kms,'cipher-algo=aes256/i);
assert.match(SQL, /jsonb_array_length\(p_payload->'rows'\)<>87/i);
assert.match(SQL, /count\(distinct x->>'placement_key'\)/i);
assert.match(SQL, /grant execute on function public\.nexus_v3360_hydrate_cj\(jsonb\) to service_role/i);
assert.match(SQL, /evidence_expires_at>clock_timestamp\(\)/i);
assert.match(SQL, /country_target_is_city_serviceability_proof',false/i);
assert.match(SQL, /city_page_programmatic_indexing_enabled',false/i);
assert.match(SQL, /disclosure_required_before_link','#ad'/i);
assert.match(SQL, /affiliate_url',null/i);
assert.match(SQL, /destination_not_in_v3360_delta/i);
assert.match(SQL, /admin_area_required_for_ambiguous_destination/i);
assert.match(SQL, /destination_validated_but_routing_disabled/i);
assert.doesNotMatch(SQL, /city_delta c where c\.routing_country_code=v_country and c\.routing_eligible/i);
assert.match(SQL, /travel_intent_not_explicit/i);
assert.match(SQL, /Sintonizado em Análise/g);
assert.doesNotMatch(SQL, /(?:insert\s+into|update|delete\s+from)\s+public\.ads\b/i);
assert.doesNotMatch(SQL, /(?:insert\s+into|update|delete\s+from)\s+public\.nexus_v370_keyword_source\b/i);
assert.doesNotMatch(SQL, /cron\.(?:schedule|unschedule)/i);
assert.match(SQL, /jobid in\(15,16,64\) and active/i);
assert.match(EDGE, /user_supplied_destination !== true/);
assert.match(EDGE, /delete body\.affiliate_url/);
assert.match(EDGE, /affiliate_url: null/);
assert.match(EDGE, /redirect_endpoint_deployed: false/);
assert.doesNotMatch(EDGE, /Response\.redirect|location\s*:/i);
assert.match(CJ, /partnerStatus: JOINED/);
assert.doesNotMatch(CJ, /partnerIds\s*:/);
assert.match(CJ, /linkCode\(pid:/);
assert.match(CJ, /serviceableAreas:/);
assert.match(CJ, /affiliate_url_recorded: false/);
assert.doesNotMatch(CJ, /TOKEN\.slice|publisher_id|company_id\s*:/i);
assert.match(GO_TEST, /console\.log = \(\) => \{\}/);
assert.doesNotMatch(GO_TEST, /r6\.location\.slice/);
assert.strictEqual(EVIDENCE.publication_state, 'internal_foundation_deployed_no_public_pages_or_redirect');
assert.strictEqual(EVIDENCE.city_evidence.validated_rows, 853);
assert.strictEqual(EVIDENCE.city_evidence.delta_rows, 816);
assert.strictEqual(EVIDENCE.cj_evidence.affiliate_urls_recorded, false);
assert.strictEqual(EVIDENCE.cj_evidence.clicks_performed, false);
assert.strictEqual(EVIDENCE.implementation.production_schema_committed, true);
assert.strictEqual(EVIDENCE.implementation.encrypted_affiliate_urls_installed, 87);
assert.strictEqual(EVIDENCE.implementation.internal_routes_enabled, 87);
assert.strictEqual(EVIDENCE.implementation.hydration_rpc_dropped, true);
assert.strictEqual(EVIDENCE.implementation.edge_function_physically_verified, true);
assert.strictEqual(EVIDENCE.implementation.city_pages_published, false);
assert.strictEqual(EVIDENCE.implementation.redirect_endpoint_deployed, false);
assert.strictEqual(sha('api/ads/go.js'), 'e77aab2895e8a194542866bf7c9e997a0fe37138638ce57125c8536009827716');
assert.strictEqual(sha('edge/jetstream/compose.ts'), 'd99ce7b5ca412102659f44d6d58f8f84f1b111f0f08865f208f13fd12cc730d0');
console.log('v3360 metropolitan expansion tests: PASS');
