#!/usr/bin/env node
'use strict';
const assert=require('assert');const crypto=require('crypto');const fs=require('fs');const path=require('path');const ROOT=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,p))).digest('hex');
const SQL=read('supabase/migrations/supabase_v3370_metropolitan_additional_batch.sql');const EDGE=read('supabase/functions/nexus-metropolitan-v3370/index.ts');const E=JSON.parse(read('docs/evidencias/v3370-metropolitan-additional-evidence.json'));
function embedded(tag){const m=SQL.match(new RegExp(`\\$${tag}\\$([\\s\\S]*?)\\$${tag}\\$::jsonb`));assert.ok(m,`missing ${tag}`);return JSON.parse(m[1]);}
const cities=embedded('v3370_city'),policies=embedded('v3370_cj');assert.strictEqual(cities.length,202);assert.deepStrictEqual(Object.fromEntries([...new Set(cities.map(x=>x.source_country_code))].sort().map(cc=>[cc,cities.filter(x=>x.source_country_code===cc).length])),{AU:51,GB:10,ID:66,IN:25,MX:50});assert.strictEqual(cities.filter(x=>x.routing_eligible).length,199);assert.deepStrictEqual(cities.filter(x=>!x.routing_eligible).map(x=>x.destination_name).sort(),['Deli Serdang','Gowa','Ogan Ilir']);assert.ok(cities.every(x=>Number(x.geonames_id)>0&&/^[a-f0-9]{64}$/.test(x.source_sha256)));assert.ok(cities.some(x=>x.destination_name==='Cidade do México'&&x.aliases.includes('Ciudad de México')));assert.ok(cities.some(x=>x.destination_name==='Jacarta'&&x.aliases.includes('Jakarta')));assert.ok(cities.some(x=>x.destination_name==='Kurnool'&&x.aliases.some(a=>/[^\u0000-\u024f]/.test(a))));assert.strictEqual(policies.length,7);assert.ok(policies.every(x=>x.country_code==='AU'&&x.locale==='en-AU'&&x.account_status==='Active'&&x.relationship_status==='joined'&&x.terms_status==='ACTIVE'&&x.pid_generated_link&&x.target_country_match));assert.ok(!policies.some(x=>Object.keys(x).some(k=>/^(?:affiliate_url|click_url|tracking_url|property_pid|token)$/i.test(k))));
assert.match(SQL,/route_enabled boolean not null default false/i);assert.match(SQL,/jsonb_array_length\(p_payload->'rows'\)<>7/i);assert.match(SQL,/pgp_sym_encrypt\(v_url,v_kms,'cipher-algo=aes256/i);assert.match(SQL,/grant execute on function public\.nexus_v3370_hydrate_cj\(jsonb\)to service_role/i);assert.match(SQL,/destination_validated_but_routing_disabled/i);assert.match(SQL,/fresh_encrypted_affiliate_route_unavailable/i);assert.match(SQL,/policy_source',v_source/i);assert.match(SQL,/country_target_is_city_serviceability_proof',false/i);assert.match(SQL,/disclosure_required_before_link','#ad'/i);assert.match(SQL,/affiliate_url',null/i);assert.doesNotMatch(SQL,/(?:insert\s+into|update|delete\s+from)\s+public\.(?:ads|nexus_v370_keyword_source|nexus_v380_keyword_vectors)\b/i);assert.doesNotMatch(SQL,/cron\.(?:schedule|unschedule)/i);assert.match(SQL,/jobid in\(15,16,64\)and active/i);
assert.match(EDGE,/user_supplied_destination !== true/);assert.match(EDGE,/delete body\.affiliate_url/);assert.match(EDGE,/affiliate_url: null/);assert.match(EDGE,/redirect_endpoint_deployed: false/);assert.doesNotMatch(EDGE,/Response\.redirect|location\s*:/i);
assert.strictEqual(E.pdf_evidence.byte_identical_prior_documents,3);assert.strictEqual(E.pdf_evidence.existing_v3340_or_v3360_rows_not_duplicated,117);assert.strictEqual(E.city_evidence.delta_rows,202);assert.strictEqual(E.city_evidence.routing_eligible_delta_rows,199);assert.strictEqual(E.cj_evidence.selected_placements,7);assert.strictEqual(E.cj_evidence.country_readiness.MX.routing_ready,false);assert.strictEqual(E.cj_evidence.country_readiness.ID.routing_ready,false);assert.strictEqual(E.implementation.production_schema_committed,true);assert.strictEqual(E.implementation.production_schema_physically_verified,true);assert.strictEqual(E.implementation.encrypted_affiliate_urls_installed,7);assert.strictEqual(E.implementation.internal_au_routes_enabled,7);assert.strictEqual(E.implementation.hydration_rpc_dropped,true);assert.strictEqual(E.implementation.edge_function_physically_verified,true);assert.strictEqual(E.implementation.city_pages_published,false);assert.strictEqual(E.implementation.redirect_endpoint_deployed,false);assert.strictEqual(sha('api/ads/go.js'),'e77aab2895e8a194542866bf7c9e997a0fe37138638ce57125c8536009827716');assert.strictEqual(sha('edge/jetstream/compose.ts'),'d99ce7b5ca412102659f44d6d58f8f84f1b111f0f08865f208f13fd12cc730d0');console.log('v3370 metropolitan additional batch tests: PASS');
