'use strict';
const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const sha = p => crypto.createHash('sha256').update(fs.readFileSync(path.join(root, p))).digest('hex');
const sql = read('supabase/migrations/supabase_v3380_cj_global_ingestion.sql');
const rollback = read('supabase/migrations/rollback_v3380_cj_global_ingestion.sql');
const edge = read('supabase/functions/nexus-cj-global-v3380/index.ts');

assert.match(sql, /^-- Nexus v3380\.0/);
assert.match(sql, /begin;[\s\S]*set local statement_timeout='4000ms';/i);
assert.match(sql, /set local lock_timeout='1000ms';/i);
assert.match(sql, /create table if not exists public\.nexus_v3380_cj_global_vault/);
assert.match(sql, /create table if not exists public\.nexus_v3380_cj_global_ingestion/);
assert.match(sql, /pgp_sym_encrypt\(/);
assert.match(sql, /key='nexus_satellites_kms'/);
assert.match(sql, /link_identity_enc bytea not null/);
assert.match(sql, /tracking_url_enc bytea not null/);
assert.match(sql, /destination_url_enc bytea/);
const vault = sql.match(/create table if not exists public\.nexus_v3380_cj_global_vault\((.*?)\n\);/s)[1];
assert.doesNotMatch(vault, /\b(?:tracking_url|destination_url|advertiser_id|advertiser_name|link_id|link_name|description|token|pid)\s+text\b/i);
assert.match(vault, /route_approved boolean not null default false/);
assert.match(vault, /routing_activated boolean not null default false/);
assert.match(sql, /country_target_is_city_serviceability_proof boolean not null default false/);
assert.match(sql, /revoke all on table public\.nexus_v3380_cj_global_vault from public,anon,authenticated,service_role/);
assert.match(sql, /security definer/ig);
assert.match(sql, /jobid=60 and active and schedule='10 seconds'/);
assert.match(sql, /jobid in\(15,16,64\) and active/);
assert.match(sql, /a\.keyword_rows<>17605/);
assert.doesNotMatch(sql, /(insert\s+into|update|delete\s+from)\s+public\.(?:ads|nexus_v370_keyword_source|nexus_v380_keyword_vectors)\b/i);
assert.match(sql, /'v3380_cj_global_bulk_routing',false/);
assert.doesNotMatch(sql, /meli\.la|56714869|5339193749/i);
assert.match(rollback, /drop table if exists public\.nexus_v3380_cj_global_vault/);

assert.match(edge, /internal_encrypted_cj_global_backlog_status/);
assert.match(edge, /public_redirect_deployed: false/);
assert.match(edge, /geo_swap_deployed: false/);
assert.match(edge, /sub_1ms_guaranteed: false/);
assert.match(edge, /sub_50ms_fallback_guaranteed: false/);
assert.match(edge, /delete body\.affiliate_url/);
assert.doesNotMatch(edge, /status\s*:\s*30[1278]|location\s*:/i);
assert.strictEqual(sha('api/ads/go.js'), 'e77aab2895e8a194542866bf7c9e997a0fe37138638ce57125c8536009827716');
assert.strictEqual(sha('edge/jetstream/compose.ts'), 'd99ce7b5ca412102659f44d6d58f8f84f1b111f0f08865f208f13fd12cc730d0');
assert.strictEqual(sha('correcoes/clique-comprovado/api/ads/go.aquitem.js'), '7ad88bb3133169bc16ce005655829375faf5d85270e4676e10134cf2fd2e80bc');
assert.strictEqual(sha('correcoes/clique-comprovado/api/ads/go.js'), '7da009550dcbad0d86b297f58ed9520e239c15d0f88a84d853ec9c703b000e9c');
const discoveryPath = path.join(root, 'docs/evidencias/v3380-cj-global-discovery.json');
if (fs.existsSync(discoveryPath)) {
  const discovery = JSON.parse(fs.readFileSync(discoveryPath, 'utf8'));
  assert.strictEqual(discovery.delta_countries_queried, 196);
  assert.strictEqual(discovery.summary.countries_ok, 196);
  assert.strictEqual(discovery.summary.countries_api_error, 0);
  assert.strictEqual(discovery.summary.total_api_records, 84100);
  assert.strictEqual(discovery.summary.protected_active_joined_travel_candidates, 1266);
  assert.strictEqual(discovery.summary.countries_with_protected_candidates, 74);
  assert.strictEqual(discovery.summary.country_target_is_city_serviceability_proof, false);
  assert.doesNotMatch(JSON.stringify(discovery), /https?:\/\//i);
}
const deployPath = path.join(root, 'docs/evidencias/v3380-cj-global-production-deploy.json');
if (fs.existsSync(deployPath)) {
  const deploy = JSON.parse(fs.readFileSync(deployPath, 'utf8'));
  assert.strictEqual(deploy.result, 'pass');
  assert.strictEqual(deploy.candidate_rows, 1266);
  assert.strictEqual(deploy.hydration.sealed, true);
  assert.strictEqual(deploy.hydration.bulk_routes_activated, 0);
  assert.strictEqual(deploy.production_verification.checks.encrypted_rows, 1266);
  assert.strictEqual(deploy.production_verification.checks.selected_fresh_routes, 19);
  assert.strictEqual(deploy.production_verification.checks.keyword_rows, 17605);
  assert.doesNotMatch(JSON.stringify(deploy), /https?:\/\//i);
}
console.log('v3380 encrypted CJ global backlog tests: PASS');
