'use strict';
const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const sha = p => crypto.createHash('sha256').update(fs.readFileSync(path.join(root, p))).digest('hex');
const sql = read('supabase/migrations/supabase_v3500_quantum_inbound.sql');
const rollback = read('supabase/migrations/rollback_v3500_quantum_inbound.sql');
const edge = read('supabase/functions/nexus-quantum-inbound-v3500/index.ts');
const stream = read('supabase/functions/nexus-edge-ingest-v3000/index.ts');
const worker = read('workers/traffic-core-v1510.js');
const workflow = read('.github/workflows/jetstream-24-7.yml');
const compose = read('edge/jetstream/compose.ts');
const legacyConsumer = read('edge/jetstream/consumer.ts');
const bench = JSON.parse(read('docs/evidencias/v3500-hnsw-benchmark.json'));
const deployEvidence = JSON.parse(read('docs/evidencias/v3500-production-deploy.json'));
const sqlDryRun = JSON.parse(read('docs/evidencias/v3500-sql-dryrun.json'));
const rollbackDryRun = JSON.parse(read('docs/evidencias/v3500-rollback-dryrun.json'));
const productionVerify = JSON.parse(read('docs/evidencias/v3500-production-verification.json'));
const edgeVerify = JSON.parse(read('docs/evidencias/v3500-edge-verification.json'));
const routeBench = JSON.parse(read('docs/evidencias/v3500-route-readiness-benchmark.json'));
const satelliteVerify = JSON.parse(read('docs/evidencias/v3500-satellite-current-verification.json'));
const socketVerify = JSON.parse(read('docs/evidencias/v3500-rfc6455-dryrun.json'));

assert.match(sql, /^-- Nexus v3500\.0/);
assert.match(sql, /begin;[\s\S]*set local statement_timeout='4000ms'/i);
assert.match(sql, /set local lock_timeout='1000ms'/i);
assert.match(sql, /nexus_v1550_outbox_logged/);
assert.match(sql, /pg_notify\('nexus_v3500_outbox'/);
assert.match(sql, /notify_is_durable',false/);
assert.match(sql, /create trigger trg_v3500_outbox_signal after insert or update/);
assert.match(sql, /nexus_v3500_cj_route_lookup_idx/);
assert.match(sql, /country_code,lower\(locale\),intent,evidence_expires_at/);
assert.match(sql, /q\.intent=lower\(btrim\(p_intent\)\)/);
assert.match(sql, /affiliate_url',null/);
assert.doesNotMatch(sql, /pgp_sym_decrypt\(/i);
assert.match(sql, /jobid in\(15,16,18,21,35,36,38,40,41,44,47,48,62,63,64,65\)/);
assert.match(sql, /jobid=60 and active and schedule='10 seconds'/);
assert.match(sql, /command='select public\.nexus_v1510_flush_event\(40\);'/);
assert.match(sql, /a\.keyword_rows<>17605/);
assert.doesNotMatch(sql, /(insert\s+into|update|delete\s+from)\s+public\.(?:ads|nexus_v370_keyword_source|nexus_v380_keyword_vectors)\b/i);
assert.match(sql, /'v3500_continuous_runtime',false/);
assert.match(sql, /'v3500_direct_merchant_fallback',false/);
assert.match(sql, /'future_reactivation_impossible',false/);
assert.doesNotMatch(sql, /commission_lossless_guaranteed',true|sub_1ms_guaranteed',true|sub_50ms_guaranteed',true/i);
assert.match(rollback, /drop trigger if exists trg_v3500_outbox_signal/);
assert.doesNotMatch(rollback, /active\s*=>\s*true/i);

assert.match(edge, /internal_reactive_core_status_and_route_readiness/);
assert.match(edge, /permanent_24x7_claimed: false/);
assert.match(edge, /continuous_runtime_provisioned: false/);
assert.match(edge, /cpu_multithreading_claimed: false/);
assert.match(edge, /cdn_country_is_human_or_city_proof: false/);
assert.match(edge, /public_redirect_deployed: false/);
assert.match(edge, /kv_fallback_deployed: false/);
assert.match(edge, /delete result\.affiliate_url/);
assert.doesNotMatch(edge, /location\s*:|status\s*:\s*30[1278]/i);

assert.match(stream, /bounded, resumable RFC 6455 ingestion session/);
assert.match(stream, /permanent_24x7_claimed:false/);
assert.match(stream, /Promise\.allSettled\(loops\)/);
assert.match(stream, /backoff\+Math\.floor\(Math\.random\(\)\*250\)/);
assert.match(worker, /WebSocket = require\('ws'\)/);
assert.match(worker, /Promise\.allSettled/);
assert.match(worker, /setTimeout\(connect, wait\)/);
assert.match(worker, /wss:\/\/nos\.lol,wss:\/\/relay\.damus\.io/);
assert.match(workflow, /NOSTR_RELAYS: "wss:\/\/nos\.lol,wss:\/\/relay\.damus\.io"/);
assert.match(workflow, /Isto NÃO é polling de dados/);
assert.doesNotMatch(worker, /setInterval\(/);
assert.match(compose, /linhas\.splice\(indice, 0, rotulo\)/);
assert.match(legacyConsumer, /human_likely_not_residential_proof/);
assert.doesNotMatch(legacyConsumer, /motivo: "residencial_humano"/);

assert.strictEqual(bench.server_version, 'PostgreSQL 17.6');
assert.strictEqual(bench.pgvector_version, '0.8.2');
assert.strictEqual(bench.samples, 250);
assert.strictEqual(bench.index_plan_observed, true);
assert.strictEqual(bench.p99_ms, 0.522);
assert.strictEqual(bench.max_ms, 437.959);
assert.strictEqual(bench.end_to_end_latency_measured, false);
assert.strictEqual(bench.sub_1ms_guaranteed, false);
assert.strictEqual(deployEvidence.result, 'installed');
assert.strictEqual(deployEvidence.migration_sha256, sha('supabase/migrations/supabase_v3500_quantum_inbound.sql'));
assert.strictEqual(sqlDryRun.result, 'pass');
assert.strictEqual(sqlDryRun.transaction_rolled_back, true);
assert.strictEqual(sqlDryRun.migration_sha256, sha('supabase/migrations/supabase_v3500_quantum_inbound.sql'));
assert.strictEqual(rollbackDryRun.result, 'pass');
assert.strictEqual(rollbackDryRun.rollback_sha256, sha('supabase/migrations/rollback_v3500_quantum_inbound.sql'));
assert.strictEqual(productionVerify.result, 'pass');
assert.strictEqual(productionVerify.physical.keyword_rows, 17605);
assert.strictEqual(productionVerify.physical.cj_fresh_routes, 19);
assert.strictEqual(productionVerify.physical.job60_ok, true);
assert.strictEqual(productionVerify.physical.legacy_pollers_active, 0);
assert.strictEqual(productionVerify.physical.shopee_inventory_present, false);
assert.strictEqual(edgeVerify.result, 'pass');
assert.strictEqual(edgeVerify.checks.public_redirect_deployed, false);
assert.strictEqual(edgeVerify.checks.affiliate_url_returned, false);
assert.strictEqual(routeBench.samples, 250);
assert(routeBench.p99_ms < 1);
assert(routeBench.max_ms > 1);
assert.strictEqual(routeBench.end_to_end_edge_latency_measured, false);
assert.strictEqual(routeBench.sub_1ms_guaranteed, false);
assert.strictEqual(satelliteVerify.result, 'partial_current_verification');
assert.strictEqual(satelliteVerify.endpoint_rejected_unauthenticated_request_http_401, 13);
assert.strictEqual(satelliteVerify.function_active_verified_currently, 9);
assert.strictEqual(satelliteVerify.function_status_currently_unverified, 4);
assert.strictEqual(satelliteVerify.permanent_24x7_proven, false);
assert.strictEqual(socketVerify.result, 'pass_with_reconnect_observed');
assert.strictEqual(socketVerify.keyword_mappings, 17605);
assert.strictEqual(socketVerify.frames, 458);
assert.strictEqual(socketVerify.accepted, 0);
assert.strictEqual(socketVerify.rpc_errors, 0);
assert.strictEqual(socketVerify.database_writes, false);
assert.strictEqual(socketVerify.permanent_24x7_proven, false);
for (const evidence of [deployEvidence, sqlDryRun, rollbackDryRun, productionVerify, edgeVerify, routeBench, satelliteVerify, socketVerify]) {
  assert.strictEqual(evidence.secrets_recorded, false);
}

assert.strictEqual(sha('api/ads/go.js'), 'e77aab2895e8a194542866bf7c9e997a0fe37138638ce57125c8536009827716');
assert.strictEqual(sha('edge/jetstream/compose.ts'), 'd99ce7b5ca412102659f44d6d58f8f84f1b111f0f08865f208f13fd12cc730d0');
assert.strictEqual(sha('correcoes/clique-comprovado/api/ads/go.aquitem.js'), '7ad88bb3133169bc16ce005655829375faf5d85270e4676e10134cf2fd2e80bc');
assert.strictEqual(sha('correcoes/clique-comprovado/api/ads/go.js'), '7da009550dcbad0d86b297f58ed9520e239c15d0f88a84d853ec9c703b000e9c');
console.log('v3500 truthful reactive inbound tests: PASS');
