'use strict';
const assert=require('assert');const crypto=require('crypto');const fs=require('fs');const path=require('path');
const root=path.join(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const sql=read('supabase/migrations/supabase_v3600_bluesky_travel_matrix.sql');
const rollback=read('supabase/migrations/rollback_v3600_bluesky_travel_matrix.sql');
const edge=read('supabase/functions/nexus-travel-matrix-v3600/index.ts');
const manifest=JSON.parse(read('data/v3600-travel-matrix.json'));
const dry=JSON.parse(read('docs/evidencias/v3600-sql-dryrun.json'));
const deploy=JSON.parse(read('docs/evidencias/v3600-production-deploy.json'));
const prod=JSON.parse(read('docs/evidencias/v3600-production-verification.json'));
const edgeVerify=JSON.parse(read('docs/evidencias/v3600-edge-verification.json'));
const bench=JSON.parse(read('docs/evidencias/v3600-route-benchmark.json'));
const accounts=JSON.parse(read('docs/evidencias/v3600-account-deployment-verification.json'));
const rollbackEvidence=JSON.parse(read('docs/evidencias/v3600-rollback-dryrun.json'));
const preservation=JSON.parse(read('docs/evidencias/v3600-preservation-verification.json'));
assert.match(sql,/^-- Nexus v3600\.0/);assert.match(sql,/begin;[\s\S]*set local statement_timeout='4000ms'/i);assert.match(sql,/set local lock_timeout='1000ms'/i);
assert.match(sql,/nexus\.v3600_travel_embeddings_json/);assert.match(sql,/jsonb_array_length\(v_payload->'rows'\)<>20/);assert.match(sql,/public\.halfvec\(384\)/);assert.match(sql,/on conflict\(country_code,destination_key\) do nothing/i);
assert.match(sql,/v_inserted not in\(0,16\)/);assert.match(sql,/nexus_v3600_destination_matrix/);assert.match(sql,/matrix count/);
assert.match(sql,/create table if not exists public\.nexus_v3600_route_readiness/);assert.match(sql,/nexus_v3600_route_readiness_idx/);assert.match(sql,/include\(route_ready,catalog_rows\)/);assert.match(sql,/readiness\)<>9/);
assert.match(sql,/third_party_estimated_bsky_app_web_traffic/);assert.match(sql,/\('US',1,48\.87/);assert.match(sql,/\('GB',2,8\.26/);assert.match(sql,/current_guarantee boolean not null default false/);
assert.match(sql,/official_bluesky_distribution',false/);assert.match(sql,/operator_supplied_search_ranking_not_independently_verified/);
assert.match(sql,/jobid in\(15,16,18,21,35,36,38,40,41,44,47,48,62,63,64,65\)/);assert.match(sql,/jobid=60 and active/);assert.match(sql,/select public\.nexus_v1510_flush_event\(40\);/);
assert.doesNotMatch(sql,/cron\.alter_job\(60/);assert.doesNotMatch(sql,/insert into public\.nexus_telegram_message_buffer/i);assert.doesNotMatch(sql,/drop trigger if exists trg_v420_legacy_buffer_closed/i);
assert.match(sql,/nexus_v420_channel_outbox/);assert.match(sql,/pacing','max 3\/min and 40\/hour per destination/);assert.match(sql,/-1004417007577/);assert.match(sql,/-1003951454560/);
assert.doesNotMatch(sql,/(insert\s+into|update|delete\s+from)\s+public\.(?:ads|nexus_v370_keyword_source|nexus_v380_keyword_vectors)\b/i);
assert.match(sql,/'affiliate_url',null/);assert.match(sql,/'timezone_proven',false/);assert.match(sql,/'human_or_residential_proven',false/);assert.match(sql,/'continuous_24x7_proven',false/);assert.match(sql,/'fallback_deployed',false/);assert.match(sql,/'sub_50ms_fallback_guaranteed',false/);assert.match(sql,/'commission_lossless_guaranteed',false/);
assert.match(rollback,/where installed_by_release='v3600\.0'/);assert.doesNotMatch(rollback,/active\s*:=\s*true|cron\.alter_job/i);
assert.match(edge,/internal_metadata_only_travel_matrix/);assert.match(edge,/release_embedding_batch/);assert.match(edge,/Promise\.all\(texts\.map\(embed\)\)/);assert.match(edge,/affiliate_url_returned: false/);assert.match(edge,/continuous_24x7_claimed: false/);assert.match(edge,/timezone_inferred_from_country: false/);assert.match(edge,/delete route\.affiliate_url/);assert.doesNotMatch(edge,/status\s*:\s*30[1278]|location\s*:/i);
assert.strictEqual(manifest.destinations.length,20);assert.strictEqual(manifest.traffic_share_snapshot.length,5);assert.strictEqual(manifest.destinations.filter(x=>x.batch===1).length,10);assert.strictEqual(manifest.destinations.filter(x=>x.batch===2).length,10);
assert.deepStrictEqual(manifest.traffic_share_snapshot.slice(0,2).map(x=>[x.country_code,x.share_pct]),[['US',48.87],['GB',8.26]]);
const keys=new Set(manifest.destinations.map(x=>`${x.batch}:${x.rank}`));assert.strictEqual(keys.size,20);
for(const d of manifest.destinations){assert(/^[A-Z]{2}$/.test(d.country_code));assert(/^[a-z]{2,3}-[A-Z]{2}$/.test(d.locale));assert(/^[A-Z]{3}$/.test(d.country_currency));assert(d.verified_networks.every(x=>d.eligible_networks.includes(x)));}
assert.strictEqual(manifest.truth_boundary.batch_2.includes('no matching official'),true);
const go=read('api/ads/go.js');assert.match(go,/X-Adsterra-Binding', TAG_BINDING/);assert.match(go,/const TAG_BINDING = 'pop=' \+ \(TAG_ADSTERRA \? 'bound' : 'none'\) \+ ';sb=' \+ \(TAG_SOCIALBAR \? 'bound' : 'none'\)/);
assert.strictEqual(sha('api/ads/go.js'),'e77aab2895e8a194542866bf7c9e997a0fe37138638ce57125c8536009827716');
assert.strictEqual(sha('edge/jetstream/compose.ts'),'d99ce7b5ca412102659f44d6d58f8f84f1b111f0f08865f208f13fd12cc730d0');
assert.strictEqual(sha('supabase/functions/nexus-copywriter-v3200/index.ts'),'974dc1558d703d0d1c9b1e1266552b679cb4bf03a4fb8ee5ab64dc8f26596d4b');
assert.strictEqual(sha('correcoes/clique-comprovado/api/ads/go.aquitem.js'),'7ad88bb3133169bc16ce005655829375faf5d85270e4676e10134cf2fd2e80bc');
assert.strictEqual(sha('correcoes/clique-comprovado/api/ads/go.js'),'7da009550dcbad0d86b297f58ed9520e239c15d0f88a84d853ec9c703b000e9c');
assert.strictEqual(dry.result,'pass');assert.strictEqual(dry.transaction_rolled_back,true);assert.strictEqual(dry.migration_sha256,sha('supabase/migrations/supabase_v3600_bluesky_travel_matrix.sql'));
assert.strictEqual(deploy.result,'installed');assert.strictEqual(deploy.migration_sha256,sha('supabase/migrations/supabase_v3600_bluesky_travel_matrix.sql'));
assert.strictEqual(deploy.manifest_sha256,sha('data/v3600-travel-matrix.json'));assert.strictEqual(deploy.indexed_readiness_rows,9);
assert.strictEqual(prod.result,'pass');assert.strictEqual(prod.physical.ads_rows,14301);assert.strictEqual(prod.physical.keyword_rows,17605);assert.strictEqual(prod.physical.keyword_vectors,11568);assert.strictEqual(prod.physical.travel_rows,108);assert.strictEqual(prod.physical.v3600_new_rows,16);assert.strictEqual(prod.physical.matrix_rows,20);assert.strictEqual(prod.physical.readiness_rows,9);assert.strictEqual(prod.physical.readiness_true,8);assert.strictEqual(prod.physical.job60.active,true);assert.strictEqual(prod.physical.legacy_pollers_active,0);
assert.strictEqual(edgeVerify.result,'pass');assert.strictEqual(edgeVerify.checks.us_route_ready,true);assert.strictEqual(edgeVerify.checks.br_route_ready,true);assert.strictEqual(edgeVerify.checks.tw_route_ready,false);assert.strictEqual(edgeVerify.checks.affiliate_url_returned,false);
assert.strictEqual(bench.result,'pass');assert.strictEqual(bench.server_side.samples,250);assert.strictEqual(bench.header_and_indexed_readiness_microbenchmark.samples,250);assert(bench.header_and_indexed_readiness_microbenchmark.p99_ms<1);assert(bench.server_side.p99_ms>1);assert(bench.edge_end_to_end.p99_ms>50);assert.strictEqual(bench.sub_1ms_guaranteed,false);assert.strictEqual(bench.sub_50ms_edge_guaranteed,false);
assert.strictEqual(accounts.result,'partial_master_only');assert.strictEqual(accounts.configured_accounts,14);assert.strictEqual(accounts.management_accessible_configured,10);assert.strictEqual(accounts.management_inaccessible_configured,4);assert.strictEqual(accounts.v3600_function_active_configured,1);assert.strictEqual(accounts.all_14_accounts_active_proven,false);
assert.strictEqual(rollbackEvidence.result,'pass');assert.strictEqual(rollbackEvidence.rollback_sha256,sha('supabase/migrations/rollback_v3600_bluesky_travel_matrix.sql'));assert.strictEqual(rollbackEvidence.transaction_rolled_back,true);
assert.strictEqual(preservation.result,'pass');assert.strictEqual(preservation.placements_modified,false);assert.strictEqual(preservation.compose_modified,false);assert.strictEqual(preservation.copywriter_v3200_modified,false);assert.strictEqual(preservation.live_api_ads_go_request_performed,false);assert.strictEqual(preservation.protected_hashes.api_ads_go_js,sha('api/ads/go.js'));assert.strictEqual(preservation.protected_hashes.compose_ts,sha('edge/jetstream/compose.ts'));
for(const e of [dry,prod,edgeVerify,bench,accounts,rollbackEvidence,preservation])assert.strictEqual(e.secrets_recorded,false);
const changed=sql+'\n'+edge+'\n'+read('data/v3600-travel-matrix.json');assert(!/sbp_[A-Za-z0-9]{20}|ghp_[A-Za-z0-9]{20}|\d{8,12}:[A-Za-z0-9_-]{20}|sb_secret_/i.test(changed));
console.log('v3600 truthful Bluesky/travel matrix tests: PASS');
