#!/usr/bin/env node
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const sql = fs.readFileSync(path.join(root, "supabase/migrations/supabase_v3680_14_gateway_evidence.sql"), "utf8");
const edge = fs.readFileSync(path.join(root, "supabase/functions/nexus-target-alignment-v3680/index.ts"), "utf8");
const fullRollback = fs.readFileSync(path.join(root, "supabase/migrations/rollback_v3680_target_alignment.sql"), "utf8");
const deploy = JSON.parse(fs.readFileSync(path.join(root, "docs/evidencias/v3680-14-project-edge-deploy.json"), "utf8"));
const post = JSON.parse(fs.readFileSync(path.join(root, "docs/evidencias/v3680-14-project-post-append-verification.json"), "utf8"));
assert.match(sql, /^begin;/m);
assert.match(sql, /set local statement_timeout='4000ms'/);
assert.match(sql, /set local lock_timeout='1000ms'/);
assert.match(sql, /exception when others then raise;/i);
assert.match(sql, /14,14,14,14,1,0,true/);
assert.match(sql, /'cross_project_transactionality_proven',false/);
assert.match(sql, /'continuous_24x7_proven',false/);
assert.doesNotMatch(sql, /(?:insert\s+into|update|delete\s+from)\s+public\.ads\b/i);
assert.match(edge, /NEXUS_MASTER_URL/);
assert.match(edge, /NEXUS_MASTER_SERVICE_ROLE_KEY/);
assert.match(edge, /single_master_no_catalog_replication/);
assert.match(fullRollback, /nexus_v3680_deployment_reach/);
assert.equal(deploy.configured_projects, 14);
assert.equal(deploy.management_accessible, 14);
assert.equal(deploy.edge_gateways_active_and_resolver_verified, 14);
assert.equal(deploy.master_logged_matrix_copies, 1);
assert.equal(deploy.satellite_catalog_copies, 0);
assert.equal(deploy.all_14_edge_gateways_proven, true);
assert.equal(deploy.continuous_24x7_proven, false);
assert.equal(post.gateways_verified, 14);
assert.equal(post.all_14_post_append_verified, true);
assert.equal(post.clicks_performed, false);
console.log(JSON.stringify({ok:true,edge_gateways_verified:14,master_matrix_copies:1,satellite_catalog_copies:0,continuous_24x7_proven:false}));
