#!/usr/bin/env node
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const migration = fs.readFileSync(path.join(root, "supabase/migrations/supabase_v3680_shopee_source_append.sql"), "utf8");
const rollback = fs.readFileSync(path.join(root, "supabase/migrations/rollback_v3680_shopee_source_append.sql"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "data/v3680-shopee-additional-source-manifest.json"), "utf8"));
assert.match(migration, /^begin;/m);
assert.match(migration, /set local statement_timeout='4000ms'/);
assert.match(migration, /set local lock_timeout='1000ms'/);
assert.match(migration, /exception when others then raise;/i);
assert.match(migration, /commit;\s*$/);
assert.doesNotMatch(migration, /https?:\/\//i);
assert.doesNotMatch(migration, /(?:insert\s+into|update|delete\s+from)\s+public\.ads\b/i);
assert.match(migration, /drop trigger trg_v3680_shopee_immutable/);
assert.match(migration, /create trigger trg_v3680_shopee_immutable/);
assert.match(migration, /v_n=1201/);
assert.match(rollback, /v_n=701/);
assert.match(rollback, /commit;\s*$/);
const block = migration.match(/\) values\n([\s\S]+?);\ncreate trigger trg_v3680_shopee_immutable/);
assert.ok(block);
assert.equal((block[1].match(/^\('/gm) || []).length, 500);
assert.doesNotMatch(block[1], /https?:\/\//i);
assert.equal(manifest.total_rows, 500);
assert.equal(manifest.product_rows, 500);
assert.equal(manifest.unique_product_item_ids, 500);
assert.equal(manifest.exact_binary_matches_to_preexisting_repository_batches, 5);
assert.equal(manifest.plaintext_urls_newly_versioned, false);
console.log(JSON.stringify({ok:true,encrypted_append_rows:500,combined_source_rows:1201,combined_unique_items:940,plaintext_urls_in_migration:false}));
