'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const sql=read('supabase/migrations/supabase_v4400_impression_yield.sql'),runtime=read('supabase/migrations/supabase_v4400_runtime_verification.sql'),rollback=read('supabase/migrations/rollback_v4400_impression_yield.sql'),edge=read('supabase/functions/nexus-impression-safety-v4400/index.ts'),copy=read('supabase/functions/nexus-copywriter-v3200/index.ts'),pre=JSON.parse(read('docs/evidencias/v4400-master-preflight.json'));
assert.match(sql,/^-- Nexus v4400\.0/);assert.match(sql,/begin;[\s\S]*statement_timeout='4000ms'/);assert.match(sql,/lock_timeout='1000ms'/);assert.match(sql,/create table public\.nexus_v4400_impression_policy/);assert.match(sql,/shadow_dom_injection_enabled boolean not null default false/);assert.match(sql,/automatic_impression_enabled boolean not null default false/);assert.match(sql,/is_bot_false_proves_humanity boolean not null default false/);assert.match(sql,/kv_404_fallback_enabled boolean not null default false/);assert.match(sql,/commission_lossless_guaranteed boolean not null default false/);assert.match(sql,/create table public\.nexus_v4400_impression_diagnostic_ledger/);assert.match(sql,/create table public\.nexus_v4400_impression_diagnostic_outbox/);assert.doesNotMatch(sql,/create unlogged table public\.nexus_v4400/i);assert.match(sql,/trg_v4400_diagnostic_to_outbox after insert/);assert.match(sql,/pg_notify\('nexus_v4400_diagnostic'/);assert.match(sql,/exception when others then raise/g);assert.doesNotMatch(sql,/(insert\s+into|update|delete\s+from)\s+public\.(?:ads|nexus_v370_keyword_source|nexus_v380_keyword_vectors|nexus_shopee_offers|nexus_host_tag_alignment)\b/i);
assert.match(sql,/jobid in\(15,16,18,21,35,36,38,40,41,44,47,48,62,63,64,65\)/);assert.match(sql,/jobid=60 and jobname='v360-tg-flush-10s'/);assert.doesNotMatch(sql,/cron\.alter_job\(60/);assert.match(sql,/v_minute>=3 or v_hour>=40/);assert.match(sql,/meta-llama\/llama-3-8b-instruct:free',false,false,false/);assert.match(sql,/liquid\/lfm-2\.5-2\.6b:free',true,true,true/);
assert.match(edge,/immutable_placement_safety_gate/);assert.match(edge,/expected_binding_header:'pop=bound;sb=bound'/);assert.match(edge,/shadow_dom_injection_enabled:false/);assert.match(edge,/automatic_impression_enabled:false/);assert.match(edge,/is_bot_false_proves_humanity:false/);assert.match(edge,/permanent_websocket_runtime:false/);assert.match(edge,/render_action:'existing_protected_interstitial_only'/);assert.doesNotMatch(edge,/new WebSocket|EdgeRuntime\.waitUntil|attachShadow|shadowRoot|wss:\/\//);
assert.match(copy,/MATRIX_VERSION = "v4400\.0"/);assert.match(copy,/Promise\.allSettled\(calls\)/);assert.match(copy,/liquid\/lfm-2\.5-2\.6b:free/);assert.match(copy,/REQUESTED_UNAVAILABLE_MODELS/);assert.match(copy,/automatic_impression_enabled: false/);assert.doesNotMatch(copy,/new WebSocket|attachShadow|shadowRoot/);
assert.strictEqual(pre.complete_bound_host_count,3);assert.strictEqual(pre.requested_models.find(x=>x.model_id==='meta-llama/llama-3-8b-instruct:free').present,false);assert.strictEqual(pre.requested_models.find(x=>x.model_id==='liquid/lfm-2.5-2.6b:free').eligible,true);
assert.match(runtime,/nexus_v4400_operator_status/);assert.match(runtime,/safe_impression_safety_matrix_ready',true/);assert.match(runtime,/automatic_impression_yield_active',false/);assert.match(runtime,/requested_full_horizontal_readiness',false/);assert.match(runtime,/copywriter_master_version',35/);assert.match(runtime,/exception when others then raise/);assert.match(rollback,/drop table if exists public\.nexus_v4400_impression_diagnostic_outbox/);assert.match(rollback,/drop function if exists public\.nexus_v4400_operator_status/);assert.doesNotMatch(rollback,/cron\.alter_job\(60/);assert.strictEqual(sha('api/ads/go.js'),'e77aab2895e8a194542866bf7c9e997a0fe37138638ce57125c8536009827716');assert.strictEqual(sha('edge/jetstream/compose.ts'),'d99ce7b5ca412102659f44d6d58f8f84f1b111f0f08865f208f13fd12cc730d0');
(async()=>{const handler=require(path.join(root,'api/ads/go.js'));const req={query:{diag:'1',brand:'shopee',site:'aquitemachadinhos',slot:'produto'},headers:{host:'aquitemachadinhos.com.br','user-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126 Safari/537.36','accept-language':'pt-BR,pt;q=0.9','sec-fetch-user':'?1'}};const res={headers:{},statusCode:0,body:'',setHeader(k,v){this.headers[k]=v},status(c){this.statusCode=c;return this},end(v=''){this.body=v;return this}};await handler(req,res);assert.strictEqual(res.statusCode,200);assert.strictEqual(res.headers['X-Adsterra-Binding'],'pop=bound;sb=bound');console.log('v4400 impression safety tests: PASS')})().catch(e=>{console.error(e);process.exit(1)});
