const cors={'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-nexus-v3750-secret','access-control-allow-methods':'GET,POST,OPTIONS'};
const headers={...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
function reply(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers})}
function env(name:string){return Deno.env.get(name)?.trim()??''}
function equal(a:string,b:string){if(!a||!b||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function expected(locale:string,subject:string){switch(locale.toLowerCase().split('-')[0]){case'pt':return`Para ${subject}, confira as especificações e condições atuais antes de decidir.`;case'es':return`Para ${subject}, verifica las especificaciones y condiciones actuales antes de decidir.`;case'fr':return`Pour ${subject}, vérifiez les spécifications et conditions actuelles avant de décider.`;case'de':return`Prüfen Sie für ${subject} die aktuellen Spezifikationen und Bedingungen, bevor Sie sich entscheiden.`;default:return`For ${subject}, verify current specifications and conditions before deciding.`}}
function norm(v:string){return v.normalize('NFKC').toLowerCase().replace(/[\p{P}\p{S}]+/gu,' ').replace(/\s+/g,' ').trim()}
function safeOutput(v:unknown,want:string){const raw=String(v??'');if(/https?:\/\/|[\r\n]/i.test(raw))return null;const text=raw.replace(/[\u0000-\u001f\u007f]+/g,' ').replace(/\s+/g,' ').trim();return norm(text)===norm(want)?text:null}
type Provider={name:string,url:string,key:string,model:string,freeCatalog:boolean};
async function call(p:Provider,prompt:string,want:string){const token=env(p.key);if(!token)throw new Error('missing_secret');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const messages=[{role:'system',content:'Return only the exact neutral sentence requested. Never add URLs, hashtags, prices, discounts, urgency, stock, sales, earnings, endorsements or personal experience.'},{role:'user',content:prompt}];const body=p.name==='groq'?{model:p.model,temperature:0,max_completion_tokens:220,reasoning_effort:'low',messages}:{model:p.model,temperature:0,max_tokens:100,messages};const h:Record<string,string>={authorization:`Bearer ${token}`,'content-type':'application/json','user-agent':'Nexus-v3750-whitehat/1.0'};if(p.url.includes('openrouter.ai')){h['HTTP-Referer']='https://aquitem-21j.pages.dev';h['X-Title']='Nexus v3750 White-Hat Replay'}const r=await fetch(p.url,{method:'POST',headers:h,body:JSON.stringify(body),signal:controller.signal});if(!r.ok)throw new Error(`http_${r.status}`);const d=await r.json();const out=safeOutput(d?.choices?.[0]?.message?.content,want);if(!out)throw new Error('output_rejected');return out}finally{clearTimeout(timer)}}
Deno.serve(async request=>{
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});
 const providers:Provider[]=[{name:'groq',url:'https://api.groq.com/openai/v1/chat/completions',key:'GROQ_API_KEY',model:'openai/gpt-oss-20b',freeCatalog:false},{name:'openrouter_gemma',url:'https://openrouter.ai/api/v1/chat/completions',key:'OPENROUTER_API_KEY',model:'google/gemma-4-26b-a4b-it:free',freeCatalog:true},{name:'openrouter_nemotron',url:'https://openrouter.ai/api/v1/chat/completions',key:'OPENROUTER_API_KEY',model:'nvidia/nemotron-3.5-lightning:free',freeCatalog:true}];
 if(request.method==='GET')return reply(200,{service:'nexus-free-copilot-v3750',version:'v3750.0',fanout:'Promise.allSettled',models:providers.map(p=>({provider:p.name,model:p.model,free_catalog_price_verified:p.freeCatalog})),cost_zero_guaranteed:false,publication_performed:false,links_generated:false});
 if(request.method!=='POST')return reply(405,{error:'method_not_allowed'});if(!equal(request.headers.get('x-nexus-v3750-secret')??'',env('NEXUS_V3750_COPILOT_SECRET')))return reply(401,{error:'unauthorized'});
 let body:Record<string,unknown>;try{body=await request.json()}catch{return reply(400,{error:'invalid_json'})}const text=String(body.text??'').replace(/[\u0000-\u001f\u007f]+/g,' ').replace(/\s+/g,' ').trim(),locale=String(body.locale??'en'),country=String(body.country_hint??'').toUpperCase();if(!text||text.length>500||!/^[a-z]{2}(-[A-Z]{2})?$/.test(locale)||(country&&!/^[A-Z]{2}$/.test(country)))return reply(422,{error:'invalid_request'});
 const subject=text.slice(0,80).replace(/[#$€£%]/g,'').trim()||'the item',want=expected(locale,subject),prompt=`Country routing hint ${country||'unknown'}; locale ${locale}. Return exactly: ${want}`;
 const settled=await Promise.allSettled(providers.map(p=>call(p,prompt,want))),status:Record<string,unknown>={},templates:Record<string,string>={};settled.forEach((r,i)=>{const p=providers[i];if(r.status==='fulfilled'){status[p.name]={ok:true,model:p.model,free_catalog_price_verified:p.freeCatalog};templates[p.name]=`${r.value}\n${country==='US'?'#ad':'#publi'}\n{{SHORT_LINK}}`}else status[p.name]={ok:false,model:p.model,reason:String(r.reason?.message??'provider_failed').slice(0,60),free_catalog_price_verified:p.freeCatalog}});const ok=Object.values(status).some(x=>(x as{ok:boolean}).ok);
 return reply(ok?200:503,{version:'v3750.0',providers:status,templates,fanout:'Promise.allSettled',country_is_context_hint:true,human_or_residential_proven:false,disclosure_own_line:true,disclosure_before_short_link_placeholder:true,links_generated:false,publication_performed:false,cost_zero_guaranteed:false});
});
