import{AhoCorasick,Pattern}from'./aho.ts';
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-nexus-v3750-secret','access-control-allow-methods':'GET,POST,OPTIONS'};
const headers={...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
function reply(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers})}
function env(name:string){return Deno.env.get(name)?.trim()??''}
function equal(a:string,b:string){if(!a||!b||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
async function sha(value:string){return[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function rpc(name:string,payload:Record<string,unknown>={}){const base=env('NEXUS_MASTER_URL'),key=env('NEXUS_MASTER_SERVICE_ROLE_KEY');if(!base||!key)throw new Error('master_binding_missing');const r=await fetch(`${base}/rest/v1/rpc/${name}`,{method:'POST',headers:{authorization:`Bearer ${key}`,apikey:key,'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`rpc_${name}_${r.status}`);return await r.json()}
function locale(v:unknown){const x=String(v??'en').trim();return/^[a-z]{2}(-[A-Z]{2})?$/.test(x)?x:'en'}
function country(v:unknown){const x=String(v??'').trim().toUpperCase();return/^[A-Z]{2}$/.test(x)?x:null}
function routeHint(c:string|null){if(c==='BR')return{market:'br_marketplaces',currency:'BRL'};if(c&&['US','GB','CA','AU','DE','FR','NL','CH','NO','SE','DK'].includes(c))return{market:'tier1_affiliate_families',currency:'strong_currency_context'};return{market:'global_context',currency:'unspecified'}}
async function copilot(text:string,loc:string,c:string|null){const base=env('NEXUS_MASTER_URL'),secret=env('NEXUS_V3750_COPILOT_SECRET');if(!base||!secret)return{attempted:false,status:{binding:false}};try{const r=await fetch(`${base}/functions/v1/nexus-free-copilot-v3750`,{method:'POST',headers:{'content-type':'application/json','x-nexus-v3750-secret':secret},body:JSON.stringify({text:text.slice(0,500),locale:loc,country_hint:c})});const d=await r.json().catch(()=>({}));const providers=d?.providers??{};return{attempted:true,status:{http:r.status,groq:Boolean(providers?.groq?.ok),openrouter_gemma:Boolean(providers?.openrouter_gemma?.ok),openrouter_nemotron:Boolean(providers?.openrouter_nemotron?.ok),publication_performed:false}}}catch{return{attempted:true,status:{http:0,groq:false,openrouter_gemma:false,openrouter_nemotron:false,publication_performed:false}}}}
const bannedKeys=new Set(['cookie','cookies','auth_token','x_token','x_url','twitter_url','browser_session','residential_proxy']);
Deno.serve(async request=>{
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});
 if(request.method==='GET')return reply(200,{service:'nexus-whitehat-replay-v3750',version:'v3750.0',sources:['synthetic_fixture','operator_export','owned_staging'],keyword_mappings:17605,x_transport:false,third_party_cookies:false,scraper:false,human_emulation:false,country_is_context_hint:true,direct_redirect:false,continuous_24x7_proven:false});
 if(request.method!=='POST')return reply(405,{error:'method_not_allowed'});
 if(!equal(request.headers.get('x-nexus-v3750-secret')??'',env('NEXUS_V3750_REPLAY_SECRET')))return reply(401,{error:'unauthorized'});
 let body:Record<string,unknown>;try{body=await request.json()}catch{return reply(400,{error:'invalid_json'})}
 if(Object.keys(body).some(k=>bannedKeys.has(k.toLowerCase())))return reply(422,{error:'forbidden_session_or_scraping_field'});
 const source=String(body.source_type??''),note=String(body.authorization_note??'').trim(),items=body.items,dryRun=body.persist!==true,ai=body.ai_preview===true;
 if(!['synthetic_fixture','operator_export','owned_staging'].includes(source)||note.length<8||note.length>240||!Array.isArray(items)||items.length<1||items.length>50)return reply(422,{error:'invalid_replay_request'});
 for(const item of items){if(!item||typeof item!=='object'||Object.keys(item as Record<string,unknown>).some(k=>bannedKeys.has(k.toLowerCase()))||typeof(item as Record<string,unknown>).text!=='string'||String((item as Record<string,unknown>).text).length>1000)return reply(422,{error:'invalid_or_forbidden_item'})}
 try{
  const snapshot=await rpc('nexus_v3750_keyword_snapshot');if(snapshot?.count!==17605||!Array.isArray(snapshot?.patterns)||snapshot.patterns.length!==17605)throw new Error('keyword_snapshot_invariant');
  const t0=performance.now(),matcher=new AhoCorasick(snapshot.patterns.map((x:Record<string,unknown>):Pattern=>({kw:String(x.kw),hash:String(x.hash)})));const buildMs=performance.now()-t0;
  const events:Record<string,unknown>[]=[],routeSummary:Record<string,number>={};let matched=0,providerCalls=0;
  for(let i=0;i<items.length;i++){const item=items[i]as Record<string,unknown>,text=String(item.text),loc=locale(item.locale),c=country(item.country_hint),matches=matcher.searchAll(text,25),hint=routeHint(c);routeSummary[hint.market]=(routeSummary[hint.market]??0)+1;if(!matches.length)continue;matched++;const pool=ai?await copilot(text,loc,c):{attempted:false,status:{disabled:true}};if(pool.attempted)providerCalls++;events.push({event_ordinal:i+1,content_sha256:await sha(text),locale:loc,country_hint:c,matched_keyword_hashes:await Promise.all(matches.map(x=>sha(x.kw))),matched_offer_refs:matches.map(x=>x.hash),provider_status:pool.status})}
  if(dryRun)return reply(200,{version:'v3750.0',dry_run:true,items:items.length,matched_items:matched,keyword_mappings:17605,aho_build_ms:Number(buildMs.toFixed(3)),provider_calls:providerCalls,route_summary:routeSummary,country_is_context_hint:true,human_or_residential_proven:false,raw_text_persisted:false,database_writes:false,publication_performed:false,direct_redirect:false,x_transport_used:false,third_party_cookie_used:false,scraper_used:false,continuous_24x7_proven:false});
  const manifest=await sha(JSON.stringify(items)),begin=await rpc('nexus_v3750_begin_replay',{p_source_type:source,p_authorization_note:note,p_manifest_sha256:manifest,p_declared_items:items.length}),batch=String(begin.batch_id);let inserted=0;
  try{if(events.length){const ingested=await rpc('nexus_v3750_ingest_replay_matches',{p_batch_id:batch,p_events:events});inserted=Number(ingested?.inserted??0)}await rpc('nexus_v3750_finish_replay',{p_batch_id:batch,p_success:true})}catch(error){try{await rpc('nexus_v3750_finish_replay',{p_batch_id:batch,p_success:false})}catch{}throw error}
  return reply(201,{version:'v3750.0',dry_run:false,batch_id:batch,declared_items:items.length,matched_items:matched,inserted_events:inserted,outbox_rows_created:inserted,keyword_mappings:17605,aho_build_ms:Number(buildMs.toFixed(3)),route_summary:routeSummary,country_is_context_hint:true,human_or_residential_proven:false,raw_text_persisted:false,publication_performed:false,direct_redirect:false,x_transport_used:false,third_party_cookie_used:false,scraper_used:false});
 }catch(error){return reply(500,{version:'v3750.0',error:'replay_failed',reason:String((error as Error)?.message??'failure').slice(0,100),state:'Sintonizado em Análise',database_partial_success_claimed:false,publication_performed:false})}
});
