const RELEASE='v4400.0';
const SECRET=Deno.env.get('NEXUS_V4400_SAFETY_SECRET')??'';
const HOSTS=new Set(['achadinhos-ad-engine.vercel.app','aquitemachadinhos.com.br','solvegrid.com.br']);
const HEADERS={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
function reply(status:number,body:Record<string,unknown>){return new Response(JSON.stringify(body),{status,headers:HEADERS})}
async function digest(value:string){const x=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(x)].map(v=>v.toString(16).padStart(2,'0')).join('')}
async function sameSecret(a:string,b:string){if(a.length<32||b.length<32)return false;const[x,y]=await Promise.all([digest(a),digest(b)]);let d=x.length^y.length;for(let i=0;i<Math.min(x.length,y.length);i++)d|=x.charCodeAt(i)^y.charCodeAt(i);return d===0}
function status(){return{service:'nexus-impression-safety-v4400',version:RELEASE,mode:'immutable_placement_safety_gate',expected_binding_header:'pop=bound;sb=bound',placement_mutation_allowed:false,shadow_dom_injection_enabled:false,automatic_impression_enabled:false,billable_impression_claimed:false,is_bot_false_proves_humanity:false,residential_human_emulation:false,permanent_websocket_runtime:false,background_reconnect_loop:false,continuous_24x7_proven:false,kv_404_fallback_enabled:false,direct_affiliate_fallback_enabled:false,sub_50ms_guaranteed:false,commission_lossless_guaranteed:false,publication_performed:false,affiliate_click_performed:false}}
Deno.serve(async request=>{
 if(request.method==='GET')return reply(200,status());
 if(request.method!=='POST')return reply(405,{error:'method_not_allowed'});
 if(!await sameSecret(request.headers.get('x-nexus-v4400-secret')??'',SECRET))return reply(401,{error:'unauthorized'});
 try{const raw=await request.text();if(new TextEncoder().encode(raw).length>8192)return reply(413,{error:'payload_too_large'});const body=JSON.parse(raw||'{}')as Record<string,unknown>;const host=String(body.host??'').toLowerCase().replace(/^www\./,'');if(!HOSTS.has(host))return reply(422,{...status(),state:'Sintonizado em Análise',reason:'host_not_in_complete_binding_set'});const cf=(request.headers.get('cf-ipcountry')??'').trim().toUpperCase();const vercel=(request.headers.get('x-vercel-ip-country')??'').trim().toUpperCase();const signed=String(body.country_hint??'').trim().toUpperCase();const country=cf||vercel||signed;const currency=country==='BR'?'BRL':country==='US'?'USD':country==='GB'?'GBP':['DE','FR'].includes(country)?'EUR':null;if(!currency)return reply(422,{...status(),state:'Sintonizado em Análise',reason:'country_outside_verified_currency_scope',country_is_context_hint:true});return reply(200,{...status(),state:'ok',host,country_hint:country,currency_context:currency,country_is_context_hint:true,render_action:'existing_protected_interstitial_only',network_request_performed:false,database_write_performed:false})}catch{return reply(422,{...status(),state:'Sintonizado em Análise',reason:'invalid_request'})}
});
