-- Nexus v3340.0 — Sovereign Global Travel & Intent Ingestion Suite.
-- Master: etbxbaaaspdcoiakifbb (PostgreSQL 17.6 / pgvector 0.8.2).
--
-- This additive migration installs 92 operator-supplied destination records and
-- same-model gte-small halfvec(384) embeddings. Embeddings are generated by the
-- already-live authenticated local Supabase.ai runtime and injected only through
-- transaction-local nexus.v3340_travel_embeddings_json during deploy.
--
-- Radical-truth boundaries:
-- - The supplied PDFs are operator references, not independently verified proof
--   of official status, daily search volume, or completeness.
-- - pgvector <=> is cosine distance. <-> is L2 and is not mislabeled here.
-- - The current Booking UK catalog EPC is 9.35 (7d) / 11.15 (3m), not 328.20.
-- - A country header is a routing hint, never proof of timezone, residence,
--   humanity, buyer intent, or a legitimate click.
-- - This resolver returns data only. It never redirects, clicks, appends an
--   undocumented parameter, changes price, or promises attribution/commission.
-- - api/ads/go.js, edge/jetstream/compose.ts, and all original placements/tags
--   remain byte-identical. No Cloudflare/shortener deployment is performed.
-- - No new polling/second loop is created. Job 60 remains the explicit 10s job.
begin;
set local statement_timeout='2000ms';
set local lock_timeout='1000ms';
set local idle_in_transaction_session_timeout='12000ms';

create or replace function public.nexus_v3340_norm(p_value text)
returns text
language sql
immutable
strict
parallel safe
as $function$
  select btrim(regexp_replace(
    translate(lower(p_value),
      'áàâãäåéèêëíìîïóòôõöúùûüçñýÿæœÁÀÂÃÄÅÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝŸÆŒ’',
      'aaaaaaeeeeiiiiooooouuuucnyyaoAAAAAAEEEEIIIIOOOOOUUUUCNYYAO '),
    '[^a-z0-9]+',' ','g'));
$function$;

create table if not exists public.nexus_v3340_travel_lexicon (
  lexicon_id             bigint generated always as identity primary key,
  country_code           text not null,
  primary_locale         text not null,
  locale_codes           text[] not null,
  admin_area             text not null,
  destination_name       text not null,
  destination_key        text generated always as (public.nexus_v3340_norm(destination_name)) stored,
  aliases                text[] not null,
  intent_terms           text[] not null,
  eligible_networks      text[] not null,
  verified_networks      text[] not null,
  source_documents       text[] not null,
  source_sha256          text[] not null,
  source_claim_scope     text not null,
  embedding_source       text not null,
  embedding              public.halfvec(384) not null,
  embedding_model        text not null,
  cosine_threshold       numeric(5,4) not null,
  disclosure_tag         text not null,
  installed_by_release   text not null,
  created_at             timestamptz not null default clock_timestamp(),
  updated_at             timestamptz not null default clock_timestamp(),
  constraint nexus_v3340_country_ck check(country_code in('US','CA','ES','FR','IT','GB')),
  constraint nexus_v3340_primary_locale_ck check(primary_locale=any(locale_codes)),
  constraint nexus_v3340_network_subset_ck check(verified_networks<@eligible_networks),
  constraint nexus_v3340_source_scope_ck check(source_claim_scope='operator_reference_not_independently_verified'),
  constraint nexus_v3340_model_ck check(embedding_model='gte-small'),
  constraint nexus_v3340_threshold_ck check(cosine_threshold between 0.75 and 0.95),
  constraint nexus_v3340_disclosure_ck check(disclosure_tag='#ad'),
  constraint nexus_v3340_release_ck check(installed_by_release='v3340.0'),
  constraint nexus_v3340_country_destination_uq unique(country_code,destination_key)
);

revoke all on table public.nexus_v3340_travel_lexicon
  from public,anon,authenticated,service_role;
revoke all on sequence public.nexus_v3340_travel_lexicon_lexicon_id_seq
  from public,anon,authenticated,service_role;

-- 92-row seed. The vectors join by (country_code,destination_name) from the
-- transaction-local payload and are never generated inside PostgreSQL.
do $install$
declare
  v_payload jsonb;
  v_rows integer;
begin
  begin
    v_payload:=nullif(current_setting('nexus.v3340_travel_embeddings_json',true),'')::jsonb;
    if v_payload is null
       or v_payload->>'model'<>'gte-small'
       or (v_payload->>'dimensions')::integer<>384
       or (v_payload->>'row_count')::integer<>92
       or jsonb_array_length(v_payload->'rows')<>92 then
      raise exception 'v3340 deploy embedding payload is absent or invalid';
    end if;

    insert into public.nexus_v3340_travel_lexicon(
      country_code,primary_locale,locale_codes,admin_area,destination_name,
      aliases,intent_terms,eligible_networks,verified_networks,
      source_documents,source_sha256,source_claim_scope,embedding_source,
      embedding,embedding_model,cosine_threshold,disclosure_tag,
      installed_by_release,updated_at
    )
    select s.country_code,s.primary_locale,s.locale_codes,s.admin_area,
      s.destination_name,s.aliases,
      case s.country_code
        when 'ES' then array['viaje','hotel','alojamiento','vuelo','reserva','vacaciones','turismo']
        when 'FR' then array['voyage','hotel','hebergement','vol','reservation','vacances','sejour','tourisme']
        when 'IT' then array['viaggio','hotel','alloggio','volo','prenotazione','vacanza','turismo']
        when 'CA' then array['travel','trip','hotel','accommodation','flight','booking','vacation','holiday','voyage','hebergement','vol','reservation','vacances','sejour']
        else array['travel','trip','hotel','accommodation','flight','booking','vacation','holiday']
      end,
      s.eligible_networks,s.verified_networks,s.source_documents,s.source_sha256,
      'operator_reference_not_independently_verified',s.embedding_source,
      (e.embedding::text)::public.halfvec(384),'gte-small',0.8000,'#ad',
      'v3340.0',clock_timestamp()
    from (values
      ('US','en-US',array['en-US']::text[],'New York','New York City',array['New York City','New York','Nova York']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: New York City, New York, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'California','Los Angeles',array['Los Angeles']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Los Angeles, California, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Florida','Miami',array['Miami']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Miami, Florida, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Florida','Orlando',array['Orlando']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Orlando, Florida, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Nevada','Las Vegas',array['Las Vegas']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Las Vegas, Nevada, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Illinois','Chicago',array['Chicago']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Chicago, Illinois, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'California','San Francisco',array['San Francisco']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: San Francisco, California, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'District of Columbia','Washington D.C.',array['Washington D.C.','Washington','Washington DC']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Washington D.C., District of Columbia, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Massachusetts','Boston',array['Boston']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Boston, Massachusetts, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Hawaii','Honolulu',array['Honolulu','Oahu','Oahu Hawaii']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Honolulu, Hawaii, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Alabama','Birmingham',array['Birmingham']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Birmingham, Alabama, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Arizona','Phoenix',array['Phoenix']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Phoenix, Arizona, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Arizona','Tucson',array['Tucson']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Tucson, Arizona, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'California','San Diego',array['San Diego']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: San Diego, California, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'California','San Jose',array['San Jose','San José']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: San Jose, California, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Colorado','Denver',array['Denver']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Denver, Colorado, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Colorado','Colorado Springs',array['Colorado Springs']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Colorado Springs, Colorado, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Georgia','Atlanta',array['Atlanta']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Atlanta, Georgia, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Florida','Tampa',array['Tampa']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Tampa, Florida, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Florida','Fort Lauderdale',array['Fort Lauderdale']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Fort Lauderdale, Florida, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Texas','Houston',array['Houston']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Houston, Texas, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Texas','San Antonio',array['San Antonio']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: San Antonio, Texas, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Texas','Dallas',array['Dallas']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Dallas, Texas, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Texas','Austin',array['Austin']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Austin, Texas, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Texas','Fort Worth',array['Fort Worth']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Fort Worth, Texas, United States. Hotel accommodation flight trip tourism booking.'),
      ('US','en-US',array['en-US']::text[],'Washington','Seattle',array['Seattle']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_eua.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['d5db350c89b5b1d786cafd35e1e71c52b71929ecd3887813394f563155be2752','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Seattle, Washington, United States. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Ontario','Toronto',array['Toronto']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Toronto, Ontario, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Ontario','Ottawa',array['Ottawa']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Ottawa, Ontario, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Ontario','Mississauga',array['Mississauga']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Mississauga, Ontario, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Ontario','Hamilton',array['Hamilton']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Hamilton, Ontario, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Ontario','London',array['London']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: London, Ontario, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','fr-CA',array['en-CA','fr-CA']::text[],'Quebec','Montreal',array['Montreal','Montréal']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Montreal, Quebec, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','fr-CA',array['en-CA','fr-CA']::text[],'Quebec','Quebec City',array['Quebec City','Québec City','Québec']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Quebec City, Quebec, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','fr-CA',array['en-CA','fr-CA']::text[],'Quebec','Laval',array['Laval']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Laval, Quebec, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','fr-CA',array['en-CA','fr-CA']::text[],'Quebec','Gatineau',array['Gatineau']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Gatineau, Quebec, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','fr-CA',array['en-CA','fr-CA']::text[],'Quebec','Longueuil',array['Longueuil']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Longueuil, Quebec, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'British Columbia','Vancouver',array['Vancouver']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Vancouver, British Columbia, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'British Columbia','Surrey',array['Surrey']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Surrey, British Columbia, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Alberta','Calgary',array['Calgary']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Calgary, Alberta, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Alberta','Edmonton',array['Edmonton']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Edmonton, Alberta, Canada. Hotel accommodation flight trip tourism booking.'),
      ('CA','en-CA',array['en-CA','fr-CA']::text[],'Manitoba','Winnipeg',array['Winnipeg']::text[],array['booking_global','ebay_epn']::text[],array['ebay_epn']::text[],array['grandes_cidades_metropolitanas_canada.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['17684a60e642616abe0072b468d5d6eb2e079c085dc833e98d6e05e969c127e9','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Winnipeg, Manitoba, Canada. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Madrid','Madrid',array['Madrid','Madri']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Madrid, Madrid, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Cataluña','Barcelona',array['Barcelona']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Barcelona, Cataluña, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Andalucía','Sevilla',array['Sevilla','Sevilha','Seville']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Sevilla, Andalucía, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Comunidad Valenciana','Valencia',array['Valencia','Valência']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Valencia, Comunidad Valenciana, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Illes Balears','Palma de Mallorca',array['Palma de Mallorca','Maiorca','Mallorca','Palma de Maiorca']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Palma de Mallorca, Illes Balears, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Illes Balears','Ibiza',array['Ibiza']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Ibiza, Illes Balears, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Andalucía','Granada',array['Granada']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Granada, Andalucía, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Andalucía','Málaga',array['Málaga','Malaga']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Málaga, Andalucía, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'País Vasco','Bilbao',array['Bilbao','Bilbau']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Bilbao, País Vasco, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'País Vasco','San Sebastián',array['San Sebastián','Donostia']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: San Sebastián, País Vasco, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Canarias','Las Palmas de Gran Canaria',array['Las Palmas de Gran Canaria','Las Palmas']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Las Palmas de Gran Canaria, Canarias, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Canarias','Santa Cruz de Tenerife',array['Santa Cruz de Tenerife']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Santa Cruz de Tenerife, Canarias, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Aragón','Zaragoza',array['Zaragoza','Saragoça']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Zaragoza, Aragón, Spain. Hotel accommodation flight trip tourism booking.'),
      ('ES','es-ES',array['es-ES']::text[],'Galicia','Santiago de Compostela',array['Santiago de Compostela']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_espanha.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['575d070eef8ff772c59e43aa706e25d5f2e1af09e0015a5b8439ef260ce21614','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Santiago de Compostela, Galicia, Spain. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Île-de-France','Paris',array['Paris']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Paris, Île-de-France, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Provence-Alpes-Côte d’Azur','Nice',array['Nice']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Nice, Provence-Alpes-Côte d’Azur, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Auvergne-Rhône-Alpes','Lyon',array['Lyon']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Lyon, Auvergne-Rhône-Alpes, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Provence-Alpes-Côte d’Azur','Marseille',array['Marseille','Marselha']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Marseille, Provence-Alpes-Côte d’Azur, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Nouvelle-Aquitaine','Bordeaux',array['Bordeaux','Bordéus']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Bordeaux, Nouvelle-Aquitaine, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Grand Est','Strasbourg',array['Strasbourg','Estrasburgo']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Strasbourg, Grand Est, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Occitanie','Toulouse',array['Toulouse']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Toulouse, Occitanie, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Hauts-de-France','Lille',array['Lille']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Lille, Hauts-de-France, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Pays de la Loire','Nantes',array['Nantes']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Nantes, Pays de la Loire, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Provence-Alpes-Côte d’Azur','Cannes',array['Cannes']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Cannes, Provence-Alpes-Côte d’Azur, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Auvergne-Rhône-Alpes','Saint-Étienne',array['Saint-Étienne','Saint-Etienne']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Saint-Étienne, Auvergne-Rhône-Alpes, France. Hotel accommodation flight trip tourism booking.'),
      ('FR','fr-FR',array['fr-FR']::text[],'Auvergne-Rhône-Alpes','Grenoble',array['Grenoble']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_franca.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['fc4621408deb3d239093120dc36f0342b7a4ee82d724f51dd3e6038b14b86509','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Grenoble, Auvergne-Rhône-Alpes, France. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Lazio','Roma',array['Roma','Rome']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Roma, Lazio, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Lombardia','Milano',array['Milano','Milan','Milão']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Milano, Lombardia, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Toscana','Firenze',array['Firenze','Florence','Florença']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Firenze, Toscana, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Veneto','Venezia',array['Venezia','Venice','Veneza']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Venezia, Veneto, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Campania','Napoli',array['Napoli','Naples','Nápoles']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Napoli, Campania, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Piemonte','Torino',array['Torino','Turin','Turim']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Torino, Piemonte, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Emilia-Romagna','Bologna',array['Bologna']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Bologna, Emilia-Romagna, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Liguria','Genova',array['Genova','Genoa','Gênova']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Genova, Liguria, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Sicilia','Palermo',array['Palermo']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Palermo, Sicilia, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Toscana','Pisa',array['Pisa']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Pisa, Toscana, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Campania','Salerno',array['Salerno']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Salerno, Campania, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Veneto','Verona',array['Verona']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Verona, Veneto, Italy. Hotel accommodation flight trip tourism booking.'),
      ('IT','it-IT',array['it-IT']::text[],'Veneto','Padova',array['Padova','Padua']::text[],array['booking_global']::text[],array[]::text[],array['grandes_cidades_metropolitanas_italia.pdf','lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['1049b01ffe88a44875be44c3108e15b263531a046967b77d187d240d5074e2c7','b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Padova, Veneto, Italy. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','London',array['London','Londres']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: London, England, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'Scotland','Edinburgh',array['Edinburgh','Edimburgo']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Edinburgh, Scotland, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','Manchester',array['Manchester']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Manchester, England, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','Liverpool',array['Liverpool']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Liverpool, England, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','Birmingham',array['Birmingham']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Birmingham, England, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'Scotland','Glasgow',array['Glasgow']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Glasgow, Scotland, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'Northern Ireland','Belfast',array['Belfast']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Belfast, Northern Ireland, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','Bristol',array['Bristol']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Bristol, England, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'Wales','Cardiff',array['Cardiff']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Cardiff, Wales, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','Oxford',array['Oxford']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Oxford, England, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','Cambridge',array['Cambridge']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: Cambridge, England, United Kingdom. Hotel accommodation flight trip tourism booking.'),
      ('GB','en-GB',array['en-GB']::text[],'England','York',array['York']::text[],array['booking_uk','ebay_epn']::text[],array['booking_uk','ebay_epn']::text[],array['lista_mundial_cidades_busca.pdf','cidades_mais_buscadas_booking 2.pdf']::text[],array['b25be5cc7171443de1d3177f4cb6bcd5aa223313ea9032b60ca9aa94ede22d89','72dab6316bf2023da82405724fa8ed75da066172dd24b8049dcceeb7dad9ab38']::text[],'Travel destination: York, England, United Kingdom. Hotel accommodation flight trip tourism booking.')
    ) as s(country_code,primary_locale,locale_codes,admin_area,destination_name,
           aliases,eligible_networks,verified_networks,source_documents,
           source_sha256,embedding_source)
    join jsonb_to_recordset(v_payload->'rows')
      as e(country_code text,destination_name text,embedding jsonb)
      using(country_code,destination_name)
    on conflict(country_code,destination_key) do update set
      primary_locale=excluded.primary_locale,
      locale_codes=excluded.locale_codes,
      admin_area=excluded.admin_area,
      destination_name=excluded.destination_name,
      aliases=excluded.aliases,
      intent_terms=excluded.intent_terms,
      eligible_networks=excluded.eligible_networks,
      verified_networks=excluded.verified_networks,
      source_documents=excluded.source_documents,
      source_sha256=excluded.source_sha256,
      source_claim_scope=excluded.source_claim_scope,
      embedding_source=excluded.embedding_source,
      embedding=excluded.embedding,
      embedding_model=excluded.embedding_model,
      cosine_threshold=excluded.cosine_threshold,
      disclosure_tag=excluded.disclosure_tag,
      installed_by_release=excluded.installed_by_release,
      updated_at=excluded.updated_at;

    get diagnostics v_rows=row_count;
    if v_rows<>92 or (select count(*) from public.nexus_v3340_travel_lexicon)<>92 then
      raise exception 'v3340 travel lexicon did not resolve to exactly 92 rows';
    end if;
    perform set_config('nexus.v3340_travel_embeddings_json','',true);
    v_payload:=null;
  exception when others then
    perform set_config('nexus.v3340_travel_embeddings_json','',true);
    v_payload:=null;
    raise;
  end;
end
$install$;

create index if not exists nexus_v3340_travel_country_locale_idx
  on public.nexus_v3340_travel_lexicon(country_code,primary_locale,destination_key);
create index if not exists nexus_v3340_travel_embedding_hnsw_idx
  on public.nexus_v3340_travel_lexicon
  using hnsw(embedding public.halfvec_cosine_ops)
  with(m=12,ef_construction=48);

-- Service-role-only, data-only travel resolver.
create or replace function public.nexus_v3340_resolve_travel(
  p_headers jsonb,
  p_destination text,
  p_intent_text text,
  p_intent_embedding text,
  p_locale text default null,
  p_preferred_network text default null
) returns jsonb
language plpgsql
security definer
set search_path='public','extensions','pg_temp'
as $function$
declare
  v_country text;
  v_source text;
  v_dest_key text;
  v_intent_key text;
  v_locale text;
  v_network text;
  v_query public.halfvec(384);
  v_similarity numeric;
  v_route_ready boolean:=false;
  v_catalog_rows integer:=0;
  v_campaign text;
  v_booking_aid text;
  v_kms text;
  v_host text;
  v_copy text;
  r public.nexus_v3340_travel_lexicon%rowtype;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    if p_headers is null or jsonb_typeof(p_headers)<>'object' then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','headers_invalidos','affiliate_url',null);
    end if;
    select upper(btrim(e.value)),lower(e.key) into v_country,v_source
      from jsonb_each_text(p_headers)e
     where lower(e.key) in('cf-ipcountry','x-vercel-ip-country')
       and btrim(e.value)<>''
     order by case lower(e.key) when 'cf-ipcountry' then 0 else 1 end,
              lower(e.key),e.key,e.value
     limit 1;
    if v_country is null or v_country!~'^[A-Z]{2}$' or v_country in('XX','T1') then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','cdn_country_unavailable','affiliate_url',null,'human_or_residential_proven',false);
    end if;
    if v_country not in('US','CA','ES','FR','IT','GB') then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','country_outside_v3340_scope','country',v_country,'affiliate_url',null,'human_or_residential_proven',false);
    end if;
    if p_destination is null or length(btrim(p_destination)) not between 2 and 100
       or p_intent_text is null or length(btrim(p_intent_text)) not between 3 and 500
       or p_intent_embedding is null or length(p_intent_embedding)>12000 then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','payload_invalid','country',v_country,'affiliate_url',null);
    end if;

    v_dest_key:=public.nexus_v3340_norm(p_destination);
    v_intent_key:=public.nexus_v3340_norm(p_intent_text);
    select l.* into r from public.nexus_v3340_travel_lexicon l
     where l.country_code=v_country
       and exists(select 1 from unnest(l.aliases)a
                   where public.nexus_v3340_norm(a)=v_dest_key)
     limit 1;
    if not found then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','destination_not_in_country_lexicon','country',v_country,'affiliate_url',null);
    end if;

    v_locale:=coalesce(nullif(btrim(p_locale),''),r.primary_locale);
    if not exists(select 1 from unnest(r.locale_codes)x where lower(x)=lower(v_locale)) then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','locale_not_supported_for_destination','country',v_country,'destination',r.destination_name,'supported_locales',r.locale_codes,'affiliate_url',null);
    end if;
    if not exists(select 1 from unnest(r.aliases)a
      where v_intent_key~('(^| )'||public.nexus_v3340_norm(a)||'( |$)')) then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','destination_absent_from_intent','country',v_country,'destination',r.destination_name,'affiliate_url',null);
    end if;
    if not exists(select 1 from unnest(r.intent_terms)t
      where v_intent_key~('(^| )'||public.nexus_v3340_norm(t)||'( |$)')) then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','travel_intent_not_explicit','country',v_country,'destination',r.destination_name,'affiliate_url',null);
    end if;

    begin
      v_query:=p_intent_embedding::public.halfvec(384);
    exception when others then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','embedding_invalid','country',v_country,'destination',r.destination_name,'affiliate_url',null);
    end;
    v_similarity:=1-(r.embedding<=>v_query);
    if v_similarity is null or v_similarity<r.cosine_threshold then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','cosine_threshold_not_met','country',v_country,'destination',r.destination_name,'cosine_similarity',round(v_similarity,6),'cosine_threshold',r.cosine_threshold,'operator','<=>','affiliate_url',null);
    end if;

    v_network:=lower(coalesce(nullif(btrim(p_preferred_network),''),
      case when v_country='GB' then 'booking_uk'
           when v_country in('US','CA') then 'ebay_epn' else '' end));
    if v_network<>'' and not v_network=any(r.eligible_networks) then
      return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','network_not_eligible_for_branch','country',v_country,'destination',r.destination_name,'eligible_networks',r.eligible_networks,'affiliate_url',null);
    end if;

    if v_network='ebay_epn' and v_country in('US','CA','GB') then
      v_host:=case v_country when 'US' then 'www.ebay.com' when 'CA' then 'www.ebay.ca' else 'www.ebay.co.uk' end;
      begin
        select value into strict v_kms from public.nexus_growth_secrets where key='nexus_satellites_kms';
        select extensions.pgp_sym_decrypt(decode(value,'hex'),v_kms)::jsonb->>'campaign_id'
          into strict v_campaign from public.nexus_growth_secrets where key='ebay_campaign_id_enc';
        select count(*) into v_catalog_rows from public.ads
         where active and advertiser ilike '%ebay%'
           and lower(substring(click_url from '^https?://([^/]+)'))=v_host
           and position(v_campaign in click_url)>0;
        v_route_ready:=v_catalog_rows>0;
        v_campaign:=null;v_kms:=null;
      exception when others then
        v_route_ready:=false;v_campaign:=null;v_kms:=null;
      end;
    elsif v_network='booking_uk' and v_country='GB' then
      begin
        select value into strict v_kms from public.nexus_growth_secrets where key='nexus_satellites_kms';
        select extensions.pgp_sym_decrypt(decode(value,'hex'),v_kms)::jsonb->>'aid'
          into strict v_booking_aid from public.nexus_growth_secrets where key='booking_uk_id_enc';
        select count(*) into v_catalog_rows from public.ads
         where active and advertiser='Booking.com United Kingdom'
           and cj_link_id=v_booking_aid;
        v_route_ready:=v_catalog_rows>0;
        v_booking_aid:=null;v_kms:=null;
      exception when others then
        v_route_ready:=false;v_booking_aid:=null;v_kms:=null;
      end;
    end if;

    v_copy:=case lower(v_locale)
      when 'es-es' then 'Opciones de viaje para '||r.destination_name||'. Consulta disponibilidad y condiciones actuales en la página del socio.'
      when 'fr-fr' then 'Options de voyage pour '||r.destination_name||'. Vérifiez les disponibilités et les conditions actuelles sur la page du partenaire.'
      when 'fr-ca' then 'Options de voyage pour '||r.destination_name||'. Vérifiez les disponibilités et les conditions actuelles sur la page du partenaire.'
      when 'it-it' then 'Opzioni di viaggio per '||r.destination_name||'. Verifica disponibilità e condizioni attuali sulla pagina del partner.'
      else 'Travel options for '||r.destination_name||'. Check current availability and terms on the partner page.' end;

    return jsonb_build_object(
      'version','v3340.0','estado',case when v_route_ready then 'ok' else 'Sintonizado em Análise' end,
      'motivo',case when v_route_ready then 'verified_catalog_route_available' else 'affiliate_route_unverified' end,
      'country',v_country,'geo_source',v_source,'destination',r.destination_name,
      'admin_area',r.admin_area,'locale',v_locale,'supported_locales',r.locale_codes,
      'lexicon_match',true,'travel_intent_explicit',true,
      'cosine_operator','<=>','cosine_similarity',round(v_similarity,6),
      'cosine_threshold',r.cosine_threshold,'embedding_model',r.embedding_model,
      'eligible_networks',r.eligible_networks,'selected_network',nullif(v_network,''),
      'verified_networks',r.verified_networks,'catalog_route_ready',v_route_ready,
      'catalog_route_rows',v_catalog_rows,
      'content_copy',v_copy,'disclosure_required_before_link',r.disclosure_tag,
      'disclosure_own_line',true,'affiliate_url',null,'shortener_path',null,
      'redirect_performed',false,'click_recorded',false,
      'tracking_identifiers_appended',false,'price_adapted',false,
      'cdn_country_is_routing_hint',true,'timezone_proven',false,
      'human_or_residential_proven',false,'high_frequency_throughput_proven',false,
      'sub_1ms_guaranteed',false,'fallback_anti_404_deployed',false,
      'sub_50ms_fallback_guaranteed',false,'commission_lossless_guaranteed',false);
  exception when others then
    begin
      perform public.nexus_v420_sintonizado('v3340-travel-route',coalesce(v_country,'unknown'),sqlstate||': '||left(sqlerrm,220));
    exception when others then null;
    end;
    return jsonb_build_object('version','v3340.0','estado','Sintonizado em Análise','motivo','resolver_error','affiliate_url',null);
  end;
end
$function$;

revoke all on function public.nexus_v3340_resolve_travel(jsonb,text,text,text,text,text)
  from public,anon,authenticated,service_role;
grant execute on function public.nexus_v3340_resolve_travel(jsonb,text,text,text,text,text)
  to service_role;

create or replace function public.nexus_v3340_operator_status()
returns jsonb
language plpgsql
security definer
set search_path='public','cron','extensions','pg_temp'
as $function$
declare
  v_logged boolean:=false;
  v_kms text;
  v_book text;
  v_ebay text;
  v_book_ready boolean:=false;
  v_ebay_us integer:=0;
  v_ebay_ca integer:=0;
  v_ebay_gb integer:=0;
  v_epc7 numeric;
  v_epc3 numeric;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    select relpersistence='p' into v_logged from pg_class
     where oid='public.nexus_v3340_travel_lexicon'::regclass;
    begin
      select value into strict v_kms from public.nexus_growth_secrets where key='nexus_satellites_kms';
      select extensions.pgp_sym_decrypt(decode(value,'hex'),v_kms)::jsonb->>'aid'
        into strict v_book from public.nexus_growth_secrets where key='booking_uk_id_enc';
      select extensions.pgp_sym_decrypt(decode(value,'hex'),v_kms)::jsonb->>'campaign_id'
        into strict v_ebay from public.nexus_growth_secrets where key='ebay_campaign_id_enc';
      select exists(select 1 from public.ads where active
        and advertiser='Booking.com United Kingdom' and cj_link_id=v_book),
        max(epc_7d_value),max(epc_3m_value)
        into v_book_ready,v_epc7,v_epc3 from public.ads
       where active and advertiser='Booking.com United Kingdom' and cj_link_id=v_book;
      select count(*) filter(where lower(substring(click_url from '^https?://([^/]+)'))='www.ebay.com'),
             count(*) filter(where lower(substring(click_url from '^https?://([^/]+)'))='www.ebay.ca'),
             count(*) filter(where lower(substring(click_url from '^https?://([^/]+)'))='www.ebay.co.uk')
        into v_ebay_us,v_ebay_ca,v_ebay_gb
        from public.ads where active and advertiser ilike '%ebay%' and position(v_ebay in click_url)>0;
      v_book:=null;v_ebay:=null;v_kms:=null;
    exception when others then
      v_book_ready:=false;v_ebay_us:=0;v_ebay_ca:=0;v_ebay_gb:=0;
      v_book:=null;v_ebay:=null;v_kms:=null;
    end;
    return jsonb_build_object(
      'version','v3340.0','observed_at',clock_timestamp(),
      'lexicon',jsonb_build_object(
        'relation_logged',v_logged,'rows',(select count(*) from public.nexus_v3340_travel_lexicon),
        'countries',(select jsonb_object_agg(country_code,n order by country_code) from (select country_code,count(*)n from public.nexus_v3340_travel_lexicon group by country_code)x),
        'embedding_model','gte-small','embedding_dimensions',384,
        'all_vectors_valid',(select bool_and(vector_dims(embedding)=384) from public.nexus_v3340_travel_lexicon),
        'cosine_operator','<=>','cosine_threshold',0.8000,
        'source_scope','operator_reference_not_independently_verified'),
      'affiliate_readiness',jsonb_build_object(
        'US',jsonb_build_object('ebay_epn',v_ebay_us>0,'booking_global',false),
        'CA',jsonb_build_object('ebay_epn',v_ebay_ca>0,'booking_global',false),
        'ES',jsonb_build_object('booking_global',false),
        'FR',jsonb_build_object('booking_global',false),
        'IT',jsonb_build_object('booking_global',false),
        'GB',jsonb_build_object('ebay_epn',v_ebay_gb>0,'booking_uk',v_book_ready)),
      'catalog_evidence',jsonb_build_object(
        'ebay_us_active_rows',v_ebay_us,'ebay_ca_active_rows',v_ebay_ca,'ebay_gb_active_rows',v_ebay_gb,
        'booking_uk_active',v_book_ready,'booking_uk_epc_7d_current',v_epc7,
        'booking_uk_epc_3m_current',v_epc3,
        'operator_epc_328_20_matches_current_catalog',coalesce(v_epc7=328.20,false)),
      'catalogs',jsonb_build_object(
        'ads_read_only_count',(select count(*) from public.ads),
        'active_ads_read_only_count',(select count(*) from public.ads where active),
        'canonical_keyword_count',(select count(*) from public.nexus_v370_keyword_source),
        'preexisting_local_vector_count',(select count(*) from public.nexus_v380_keyword_vectors)),
      'runtime',jsonb_build_object(
        'database_resolver_ready',true,
        'supabase_edge_deployed',exists(
          select 1 from public.nexus_v3000_capability_registry
           where capability='v3340_edge_deployment' and enabled
             and evidence->>'supabase_edge_deployed'='true'
        ),
        'cloudflare_pages_deployed',false,'shortener_modified',false,
        'go_modified',false,'compose_modified',false,'polling_job_created',false),
      'telegram',jsonb_build_object(
        'job_60',(select jsonb_build_object('active',active,'schedule',schedule,'command',command) from cron.job where jobid=60),
        'master_outbox_persistence',(select case relpersistence when 'u' then 'UNLOGGED' else 'NOT_UNLOGGED' end from pg_class where oid='public.nexus_v420_channel_outbox'::regclass),
        'satellite_outbox_persistence',(select case relpersistence when 'p' then 'LOGGED' else 'NOT_LOGGED' end from pg_class where oid='public.nexus_v1550_outbox_logged'::regclass),
        'pacing_per_destination','3/min and 40/hour',
        'channels',(select jsonb_agg(jsonb_build_object('channel_key',channel_key,'chat_id',chat_id,'source_relation',source_relation,'enabled',enabled) order by channel_key) from public.nexus_v420_channel_routes where channel_key in('grupo_cliques','atendimento'))),
      'cumulative',jsonb_build_object(
        'shein_v3330_preserved',coalesce((public.nexus_v3330_operator_status()#>>'{vault,installed}')::boolean,false),
        'amazon_v3320_preserved',coalesce((public.nexus_v3320_operator_status()#>>'{regional_readiness,BR}')::boolean,false),
        'aliexpress_v3310_preserved',coalesce((public.nexus_v3310_operator_status()#>>'{vault,installed}')::boolean,false)),
      'policy',jsonb_build_object('copy_policy_version','v3200.0','activation_profile','v3340.0','disclosure_own_line_before_link',true),
      'claims',jsonb_build_object(
        'cdn_country_proves_timezone',false,'human_or_residential_proven',false,
        'high_frequency_throughput_proven',false,'sub_1ms_guaranteed',false,
        'fallback_anti_404_deployed',false,'sub_50ms_fallback_guaranteed',false,
        'commission_lossless_guaranteed',false,'redirect_performed',false,'click_recorded',false));
  exception when others then
    begin perform public.nexus_v420_sintonizado('v3340-operator-status',null,sqlstate||': '||left(sqlerrm,220)); exception when others then null; end;
    return jsonb_build_object('version','v3340.0','state','Sintonizado em Análise','observed_at',clock_timestamp());
  end;
end
$function$;

revoke all on function public.nexus_v3340_operator_status()
  from public,anon,authenticated,service_role;
grant execute on function public.nexus_v3340_operator_status() to service_role;

update public.nexus_v3200_copy_policies
   set active=true,
       directives=directives||jsonb_build_object(
         'activation_profile','v3340.0','travel_locales',jsonb_build_array('en-US','en-CA','fr-CA','es-ES','fr-FR','it-IT','en-GB'),
         'travel_disclosure_tier1','#ad','disclosure_own_line_before_link',true,
         'travel_neutral_factual_copy',true,'travel_countdown_allowed',false,
         'travel_fake_endorsement_allowed',false,'cdn_country_is_human_proof',false,
         'cloudflare_pages_deployed',false,'shortener_modified',false,
         'fallback_anti_404_deployed',false,'sub_1ms_guaranteed',false,
         'sub_50ms_fallback_guaranteed',false,'commission_lossless_guaranteed',false),
       checked_at=clock_timestamp()
 where policy_version='v3200.0';

insert into public.nexus_v3000_capability_registry(capability,enabled,evidence,checked_at) values
 ('v3340_travel_lexicon',true,jsonb_build_object('rows',92,'countries',jsonb_build_object('US',26,'CA',15,'ES',14,'FR',12,'IT',13,'GB',12),'relation_logged',true,'source_scope','operator_reference_not_independently_verified'),clock_timestamp()),
 ('v3340_travel_vectors',true,jsonb_build_object('rows',92,'model','gte-small','dimensions',384,'operator','<=>','metric','cosine_distance','threshold',0.8000,'preexisting_canonical_vectors_mutated',false),clock_timestamp()),
 ('v3340_affiliate_routes',true,jsonb_build_object('US',jsonb_build_object('ebay_epn',true,'booking_global',false),'CA',jsonb_build_object('ebay_epn',true,'booking_global',false),'ES',jsonb_build_object('booking_global',false),'FR',jsonb_build_object('booking_global',false),'IT',jsonb_build_object('booking_global',false),'GB',jsonb_build_object('booking_uk',true,'ebay_epn',true),'redirect_enabled',false),clock_timestamp()),
 ('v3340_booking_epc_claim',false,jsonb_build_object('operator_claim_usd',328.20,'current_catalog_epc_7d',9.35,'current_catalog_epc_3m',11.15,'reason','operator claim does not match current active Booking UK catalog row'),clock_timestamp()),
 ('v3340_edge_deployment',false,jsonb_build_object('supabase_edge_deployed',false,'cloudflare_pages_deployed',false,'shortener_modified',false,'go_modified',false,'compose_modified',false,'reason','pending physical Supabase postdeploy evidence; Cloudflare credential invalid'),clock_timestamp()),
 ('v3340_fallback_anti_404',false,jsonb_build_object('cloudflare_credential_currently_valid',false,'verified_kv_binding',false,'anti_404_path',false,'sub_50ms_guaranteed',false,'commission_lossless_guaranteed',false),clock_timestamp())
on conflict(capability) do update set enabled=excluded.enabled,evidence=excluded.evidence,checked_at=excluded.checked_at;

-- Atomic catalog, vector, ACL, cumulative and Telegram assertions.
do $assert$
declare
  v_persistence "char";
  v_status jsonb;
begin
  if (select count(*) from public.nexus_v3340_travel_lexicon)<>92 then raise exception 'v3340 row count failed'; end if;
  if (select jsonb_object_agg(country_code,n order by country_code) from (select country_code,count(*)n from public.nexus_v3340_travel_lexicon group by country_code)x)
     <>jsonb_build_object('US',26,'CA',15,'ES',14,'FR',12,'IT',13,'GB',12) then raise exception 'v3340 country matrix failed'; end if;
  if exists(select 1 from public.nexus_v3340_travel_lexicon where vector_dims(embedding)<>384 or embedding_model<>'gte-small') then raise exception 'v3340 vector dimensions/model failed'; end if;
  if (select count(distinct encode(extensions.digest(embedding::text,'sha256'),'hex')) from public.nexus_v3340_travel_lexicon)<>92 then raise exception 'v3340 embeddings are not unique'; end if;
  select relpersistence into v_persistence from pg_class where oid='public.nexus_v3340_travel_lexicon'::regclass;
  if v_persistence<>'p'::"char" then raise exception 'v3340 lexicon is not LOGGED'; end if;
  if (select count(*) from public.ads)<>14301 or (select count(*) from public.ads where active)<>12165 or (select count(*) from public.nexus_v370_keyword_source)<>17605 or (select count(*) from public.nexus_v380_keyword_vectors)<>11568 then raise exception 'v3340 read-only catalogs drifted'; end if;
  if not exists(select 1 from public.nexus_shein_campaign_vault where network_id=7)
     or not exists(select 1 from public.nexus_amazon_campaign_vault where network_id=6 and region_code='BR')
     or not exists(select 1 from public.nexus_aliexpress_campaign_vault where network_id=5) then raise exception 'v3340 cumulative vault invariant failed'; end if;
  if has_table_privilege('anon','public.nexus_v3340_travel_lexicon','select') or has_table_privilege('authenticated','public.nexus_v3340_travel_lexicon','select') or has_table_privilege('service_role','public.nexus_v3340_travel_lexicon','select') then raise exception 'v3340 lexicon table exposed'; end if;
  if has_function_privilege('anon','public.nexus_v3340_resolve_travel(jsonb,text,text,text,text,text)','execute') or has_function_privilege('authenticated','public.nexus_v3340_resolve_travel(jsonb,text,text,text,text,text)','execute') or not has_function_privilege('service_role','public.nexus_v3340_resolve_travel(jsonb,text,text,text,text,text)','execute') then raise exception 'v3340 resolver ACL failed'; end if;
  if has_function_privilege('anon','public.nexus_v3340_operator_status()','execute') or has_function_privilege('authenticated','public.nexus_v3340_operator_status()','execute') or not has_function_privilege('service_role','public.nexus_v3340_operator_status()','execute') then raise exception 'v3340 status ACL failed'; end if;
  if not exists(select 1 from cron.job where jobid=60 and active and jobname='v360-tg-flush-10s' and schedule='10 seconds' and command='select public.nexus_v1510_flush_event(40);') then raise exception 'Job 60 drifted'; end if;
  if exists(select 1 from cron.job where jobid in(15,16,64) and active) then raise exception 'protected high-frequency jobs reactivated'; end if;
  select relpersistence into v_persistence from pg_class where oid='public.nexus_v420_channel_outbox'::regclass;
  if v_persistence<>'u'::"char" then raise exception 'master outbox not UNLOGGED'; end if;
  select relpersistence into v_persistence from pg_class where oid='public.nexus_v1550_outbox_logged'::regclass;
  if v_persistence<>'p'::"char" then raise exception 'satellite outbox not LOGGED'; end if;
  if not exists(select 1 from public.nexus_v420_channel_routes where channel_key='grupo_cliques' and enabled and chat_id=-1004417007577 and source_relation='public.ads_clicks') or not exists(select 1 from public.nexus_v420_channel_routes where channel_key='atendimento' and enabled and chat_id=-1003951454560 and source_relation='public.nexus_v385_nostr_mentions') then raise exception 'CLIQUES/ATENDIMENTO separation drifted'; end if;
  v_status:=public.nexus_v3340_operator_status();
  if v_status#>>'{catalog_evidence,operator_epc_328_20_matches_current_catalog}'<>'false' or (v_status#>>'{catalog_evidence,booking_uk_epc_7d_current}')::numeric<>9.35 or (v_status#>>'{catalog_evidence,booking_uk_epc_3m_current}')::numeric<>11.15 then raise exception 'Booking UK EPC truth boundary failed'; end if;
end
$assert$;

commit;
