-- =============================================================================
-- supabase_v420_channel_separation.sql
-- Sovereign Channel Separation & Luxury Layout Restruct v420.0
-- Banco-alvo auditado: etbxbaaaspdcoiakifbb (NexusPlataforma)
-- Data: 2026-09-13
--
-- Princípios operacionais:
--   * migração atômica e idempotente;
--   * roteamento 1:1 imposto por CHECK + UNIQUE + FK composta;
--   * lotes consolidados, nunca payload unitário bruto;
--   * outbox UNLOGGED consumida com FOR UPDATE SKIP LOCKED;
--   * submissão pg_net + recibo persistente + DELETE da outbox na mesma transação;
--   * sem retry de Telegram após submissão (at-most-once; não duplica na madrugada);
--   * catálogo public.ads e suas materialized views não são alterados e ficam
--     somente-leitura para os papéis expostos pela API;
--   * statement_timeout=2000 ms e lock_timeout=1000 ms em toda função de runtime.
-- =============================================================================

begin;
set local statement_timeout = '2000ms';
set local lock_timeout = '1000ms';

-- Guarda transacional: a migração aborta se tocar no total/total ativo do catálogo.
create temporary table nexus_v420_catalog_guard on commit drop as
select count(*)::bigint as total,
       count(*) filter (where active is true)::bigint as ativos
from public.ads;

-- -----------------------------------------------------------------------------
-- 1. Catálogo: estritamente read-only para PostgREST/cliente.
-- O owner postgres permanece como única via administrativa para futuros refreshes.
-- -----------------------------------------------------------------------------
revoke all on table public.ads from anon, authenticated, service_role;
grant select on table public.ads to anon, authenticated, service_role;
grant select on table public.nexus_public_offers_ordered_mv to anon, authenticated, service_role;
grant select on table public.nexus_public_offers_master_mv to anon, authenticated, service_role;
comment on table public.ads is
  'v420: catálogo mestre; somente leitura para anon/authenticated/service_role. Manutenção apenas pelo owner postgres.';

-- -----------------------------------------------------------------------------
-- 2. Fonte C2 formal (não existia no catálogo PostgreSQL na auditoria inicial).
-- Guarda apenas fatos comerciais com preço BRL e URL HTTPS medidos pelo produtor.
-- -----------------------------------------------------------------------------
create table if not exists public.nexus_telegram_c2_ofertas (
  id                    bigint generated by default as identity primary key,
  source_key            text not null unique,
  offer_id              text,
  titulo                text not null,
  loja                  text,
  preco_brl             numeric(14,2) not null check (preco_brl > 0),
  preco_de_brl          numeric(14,2) check (preco_de_brl is null or preco_de_brl > 0),
  cupom                  text,
  click_url              text not null check (click_url ~* '^https://[^[:space:]]+$'),
  action_url             text not null check (action_url ~* '^https://(www\.)?aquitemachadinhos\.com\.br/go\?'),
  button_text            text not null default 'Ver oferta',
  metadata               jsonb not null default '{}'::jsonb,
  criado_em              timestamptz not null default now()
);
comment on table public.nexus_telegram_c2_ofertas is
  'v420: snapshots comerciais BRL verificados; fonte exclusiva do canal Ofertas Brasil.';

alter table public.nexus_telegram_c2_ofertas enable row level security;
revoke all on table public.nexus_telegram_c2_ofertas from anon, authenticated, service_role;
revoke all on sequence public.nexus_telegram_c2_ofertas_id_seq from anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 3. Mapa 1:1 estanque. As combinações válidas estão fechadas no próprio CHECK.
-- IDs/títulos foram verificados via Telegram Bot API em 13/09/2026.
-- -----------------------------------------------------------------------------
create table if not exists public.nexus_v420_channel_routes (
  source_relation text primary key,
  channel_key      text not null unique,
  chat_id          bigint not null unique,
  channel_title    text not null,
  layout_key       text not null unique,
  enabled          boolean not null default true,
  verified_at      timestamptz not null,
  constraint nexus_v420_route_exact_ck check (
    (source_relation, channel_key, chat_id, layout_key) in (
      ('public.ads_clicks',                'grupo_cliques', -1004417007577, 'clicks_ledger'),
      ('public.nexus_v385_nostr_mentions', 'atendimento',   -1003951454560, 'sentinel_capture'),
      ('public.affiliate_conversions',     'vendas_real',   -1003987455421, 'cash_close'),
      ('public.nexus_telegram_c2_ofertas', 'ofertas',       -1004317377063, 'offer_buttons')
    )
  ),
  unique (source_relation, channel_key)
);

insert into public.nexus_v420_channel_routes
  (source_relation, channel_key, chat_id, channel_title, layout_key, enabled, verified_at)
values
  ('public.ads_clicks',                'grupo_cliques', -1004417007577, 'CLIQUES 💰💵',          'clicks_ledger',    true, '2026-09-13 00:00:00-03'),
  ('public.nexus_v385_nostr_mentions', 'atendimento',   -1003951454560, 'CAPTURA E ATENDIMENTO', 'sentinel_capture', true, '2026-09-13 00:00:00-03'),
  ('public.affiliate_conversions',     'vendas_real',   -1003987455421, 'VENDAS 💵💰',            'cash_close',       true, '2026-09-13 00:00:00-03'),
  ('public.nexus_telegram_c2_ofertas', 'ofertas',       -1004317377063, 'Ofertas Brasil',          'offer_buttons',    true, '2026-09-13 00:00:00-03')
on conflict (source_relation) do update
set channel_key   = excluded.channel_key,
    chat_id       = excluded.chat_id,
    channel_title = excluded.channel_title,
    layout_key    = excluded.layout_key,
    enabled       = excluded.enabled,
    verified_at   = excluded.verified_at;

alter table public.nexus_v420_channel_routes enable row level security;
revoke all on table public.nexus_v420_channel_routes from anon, authenticated, service_role;

-- Registro durável de cada fato: uma fonte/PK só entra uma vez em toda a vida.
create table if not exists public.nexus_v420_event_registry (
  registry_id     bigint generated always as identity primary key,
  source_relation text not null,
  source_pk       text not null,
  channel_key     text not null,
  state           text not null default 'queued'
                  check (state in ('queued','submitted','delivered','failed','dropped')),
  request_id      bigint,
  registered_at   timestamptz not null default now(),
  submitted_at    timestamptz,
  finalized_at    timestamptz,
  unique (source_relation, source_pk),
  foreign key (source_relation, channel_key)
    references public.nexus_v420_channel_routes (source_relation, channel_key)
);
create index if not exists nexus_v420_registry_request_idx
  on public.nexus_v420_event_registry (request_id) where request_id is not null;

-- Buffer efêmero novo. O registro acima mantém a idempotência após o DELETE.
create unlogged table if not exists public.nexus_v420_channel_outbox (
  id              bigint generated always as identity primary key,
  registry_id     bigint not null unique references public.nexus_v420_event_registry(registry_id) on delete cascade,
  source_relation text not null,
  source_pk       text not null,
  channel_key     text not null,
  payload         jsonb not null,
  enqueued_at     timestamptz not null default now(),
  unique (source_relation, source_pk),
  foreign key (source_relation, channel_key)
    references public.nexus_v420_channel_routes (source_relation, channel_key)
);
create index if not exists nexus_v420_outbox_channel_idx
  on public.nexus_v420_channel_outbox (channel_key, id);

create table if not exists public.nexus_v420_dispatch_log (
  id               bigint generated always as identity primary key,
  request_id       bigint not null unique,
  channel_key      text not null references public.nexus_v420_channel_routes(channel_key),
  chat_id          bigint not null,
  source_relation  text not null,
  source_pks        text[] not null,
  event_count       integer not null check (event_count > 0),
  body_sha256       text not null,
  submitted_at      timestamptz not null default now(),
  reconciled_at     timestamptz,
  http_status       integer,
  telegram_ok       boolean,
  response_preview text
);
create index if not exists nexus_v420_dispatch_pending_idx
  on public.nexus_v420_dispatch_log (submitted_at)
  where reconciled_at is null;

alter table public.nexus_v420_event_registry enable row level security;
alter table public.nexus_v420_channel_outbox enable row level security;
alter table public.nexus_v420_dispatch_log enable row level security;
revoke all on table public.nexus_v420_event_registry,
                           public.nexus_v420_channel_outbox,
                           public.nexus_v420_dispatch_log
  from anon, authenticated, service_role;
revoke all on sequence public.nexus_v420_event_registry_registry_id_seq,
                              public.nexus_v420_channel_outbox_id_seq,
                              public.nexus_v420_dispatch_log_id_seq
  from anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 4. Utilitários fail-closed.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_v420_html_escape(p_text text)
returns text
language sql
immutable
parallel safe
as $function$
  select replace(replace(replace(replace(replace(coalesce(p_text,''),
         '&','&amp;'), '<','&lt;'), '>','&gt;'), '"','&quot;'), '''','&#39;');
$function$;

create or replace function public.nexus_v420_sintonizado(
  p_job text, p_target text, p_detail text
) returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    insert into public.nexus_cron_telemetry(job,status,target_host,http_status,message)
    select left(coalesce(p_job,'v420'),100), 'Sintonizado em Análise',
           left(p_target,200), 0, left(coalesce(p_detail,'sem detalhe'),500)
    where not exists (
      select 1 from public.nexus_cron_telemetry
       where job = left(coalesce(p_job,'v420'),100)
         and coalesce(target_host,'') = coalesce(left(p_target,200),'')
         and message = left(coalesce(p_detail,'sem detalhe'),500)
         and created_at > now() - interval '1 minute'
    );
  exception when others then
    null;
  end;
end;
$function$;

-- Frota analítica: os 13 PostgRESTs recebem submissões pg_net assíncronas. Cada
-- nó é isolado por EXCEPTION, com os mesmos limites do Job 60; resposta instável
-- é reconciliada e removida de net._http_response para liberar recursos.
create or replace function public.nexus_v365_fleet_dispatch(
  p_evento jsonb,
  p_max_minuto integer default 3,
  p_max_hora integer default 40
) returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions', 'net', 'pg_temp'
as $function$
declare
  r record;
  v_hmac text;
  v_corpo text;
  v_req bigint;
  v_porteiro jsonb;
  v_n integer := 0;
  v_contido integer := 0;
  v_falhas integer := 0;
  v_kms text;
  v_cred text;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    if p_evento is null or jsonb_typeof(p_evento)<>'object'
       or btrim(coalesce(p_evento->>'keyword',''))=''
       or btrim(coalesce(p_evento->>'link',p_evento->>'source_url',''))='' then
      return jsonb_build_object('ok',false,'motivo','evento_analitico_incompleto');
    end if;
    select value into v_kms from public.nexus_growth_secrets where key='nexus_satellites_kms';
    if coalesce(btrim(v_kms),'')='' then
      perform public.nexus_v420_sintonizado('v420-fleet','13-satellites','KMS ausente');
      return jsonb_build_object('sintonizado',true,'motivo','Sintonizado em Análise');
    end if;
    v_corpo:=p_evento::text;

    for r in
      select node,url,secret_enc,project_ref
      from public.nexus_v360_node_endpoints
      where ativo and secret_enc is not null
      order by node
    loop
      begin
        v_porteiro:=public.nexus_v360_tg_gate(
          'node:'||r.node,'disp:'||to_char(now(),'YYYY-MM-DD HH24:MI'),
          1,greatest(1,least(coalesce(p_max_minuto,3),10)),
          greatest(1,least(coalesce(p_max_hora,40),100)));
        if not coalesce((v_porteiro->>'pode')::boolean,false) then
          v_contido:=v_contido+1;
          insert into public.nexus_v365_fleet_dispatch_log(node,evento,veredito)
          values(r.node,coalesce(p_evento->>'tipo','stream'),
                 'contido: '||coalesce(v_porteiro->>'motivo','limite'));
          continue;
        end if;

        v_cred:=extensions.pgp_sym_decrypt(decode(r.secret_enc,'hex'),v_kms);
        if coalesce(btrim(v_cred),'')='' then raise exception 'credencial decifrada vazia'; end if;
        v_hmac:=public.nexus_v360_webhook_sign(v_corpo,v_kms);
        select net.http_post(
          url:=r.url,
          headers:=jsonb_build_object(
            'apikey',v_cred,'Authorization','Bearer '||v_cred,
            'Content-Type','application/json','Prefer','return=minimal',
            'X-Nexus-Event',coalesce(p_evento->>'tipo','stream_match'),
            'X-Nexus-Node',r.node,
            'X-Nexus-Signature-256','sha256='||v_hmac),
          body:=jsonb_build_object(
            'source_url',coalesce(p_evento->>'link',p_evento->>'source_url'),
            'target_keyword',p_evento->>'keyword',
            'platform',coalesce(p_evento->>'platform','bluesky'),
            'author_handle',coalesce(p_evento->>'casa',p_evento->>'author_handle','nexus'),
            'mention_text',left(coalesce(p_evento->>'produto',p_evento->>'texto',''),900),
            'language',coalesce(p_evento->>'language',case when upper(coalesce(p_evento->>'country','BR'))='BR' then 'pt' else 'en' end)),
          timeout_milliseconds:=1000
        ) into v_req;
        if v_req is null then raise exception 'pg_net sem request_id'; end if;
        insert into public.nexus_v365_fleet_dispatch_log(node,evento,request_id,veredito)
        values(r.node,coalesce(p_evento->>'tipo','stream'),v_req,'despachado v420');
        v_n:=v_n+1;
      exception when others then
        v_falhas:=v_falhas+1;
        perform public.nexus_v420_sintonizado('v420-fleet',r.node,
          'Sintonizado em Análise · '||sqlstate||': '||left(sqlerrm,200));
        insert into public.nexus_v365_fleet_dispatch_log(node,evento,veredito)
        values(r.node,coalesce(p_evento->>'tipo','stream'),
               'Sintonizado em Análise: '||left(sqlerrm,120));
      end;
    end loop;
    return jsonb_build_object('despachados',v_n,'contidos',v_contido,'falhas',v_falhas,
      'nos_ativos',(select count(*) from public.nexus_v360_node_endpoints where ativo));
  exception when others then
    perform public.nexus_v420_sintonizado('v420-fleet','13-satellites',
      'Sintonizado em Análise · '||sqlstate||': '||left(sqlerrm,220));
    return jsonb_build_object('sintonizado',true,'motivo','Sintonizado em Análise');
  end;
end;
$function$;

create or replace function public.nexus_v365_fleet_consume()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'net', 'pg_temp'
as $function$
declare
  r record;
  v_res jsonb;
  v_http integer;
  v_ok integer:=0;
  v_err integer:=0;
  v_pend integer:=0;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    for r in
      select id,node,request_id from public.nexus_v365_fleet_dispatch_log
      where request_id is not null and http is null order by id limit 60
      for update skip locked
    loop
      begin
        v_res:=null;
        select to_jsonb(x) into v_res from net._http_response x where x.id=r.request_id;
        if v_res is null then v_pend:=v_pend+1; continue; end if;
        v_http:=coalesce((v_res->>'status_code')::integer,0);
        update public.nexus_v365_fleet_dispatch_log
        set http=v_http,
            veredito=case when v_http in(200,201) then 'espelhado (http '||v_http||')'
                          else 'Sintonizado em Análise · HTTP '||v_http end
        where id=r.id;
        delete from net._http_response where id=r.request_id;
        if v_http in(200,201) then v_ok:=v_ok+1;
        else
          v_err:=v_err+1;
          perform public.nexus_v420_sintonizado('v420-fleet-network',r.node,
            'Sintonizado em Análise · HTTP '||v_http);
        end if;
      exception when others then
        v_err:=v_err+1;
        perform public.nexus_v420_sintonizado('v420-fleet-consume',r.node,
          'Sintonizado em Análise · '||sqlstate||': '||left(sqlerrm,200));
        update public.nexus_v365_fleet_dispatch_log
          set veredito='Sintonizado em Análise: '||left(sqlerrm,100) where id=r.id;
      end;
    end loop;
    return jsonb_build_object('espelhados',v_ok,'falhas',v_err,'pendentes',v_pend);
  exception when others then
    perform public.nexus_v420_sintonizado('v420-fleet-consume','13-satellites',
      'Sintonizado em Análise · '||sqlstate||': '||left(sqlerrm,200));
    return jsonb_build_object('sintonizado',true,'motivo','Sintonizado em Análise');
  end;
end;
$function$;

revoke all on function public.nexus_v365_fleet_dispatch(jsonb,integer,integer),
                       public.nexus_v365_fleet_consume()
  from public,anon,authenticated,service_role;
grant execute on function public.nexus_v365_fleet_dispatch(jsonb,integer,integer) to service_role;

create or replace function public.nexus_v420_enqueue(
  p_source_relation text,
  p_source_pk text,
  p_channel_key text,
  p_payload jsonb
) returns bigint
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_registry bigint;
  v_outbox bigint;
  v_inserted integer;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    if p_source_pk is null or btrim(p_source_pk) = '' or p_payload is null then
      return null;
    end if;
    if not exists (
      select 1 from public.nexus_v420_channel_routes
       where source_relation = p_source_relation
         and channel_key = p_channel_key
         and enabled
    ) then
      perform public.nexus_v420_sintonizado('v420-enqueue',p_source_relation,
        'rota 1:1 inexistente ou desativada; evento recusado');
      return null;
    end if;

    insert into public.nexus_v420_event_registry(source_relation,source_pk,channel_key)
    values (p_source_relation,left(p_source_pk,240),p_channel_key)
    on conflict (source_relation,source_pk) do nothing
    returning registry_id into v_registry;
    get diagnostics v_inserted = row_count;
    if v_inserted = 0 then
      return null; -- já enfileirado/submetido: contenção definitiva de duplicidade
    end if;

    insert into public.nexus_v420_channel_outbox
      (registry_id,source_relation,source_pk,channel_key,payload)
    values
      (v_registry,p_source_relation,left(p_source_pk,240),p_channel_key,p_payload)
    returning id into v_outbox;
    return v_outbox;
  exception when others then
    perform public.nexus_v420_sintonizado('v420-enqueue',p_source_relation,
      sqlstate || ': ' || left(sqlerrm,320));
    return null;
  end;
end;
$function$;

-- -----------------------------------------------------------------------------
-- 5. Triggers das quatro fontes. Sem backfill: o patch não reenvia fatos antigos.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_v420_ads_click_enqueue()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  c_bot constant text := '(bot|crawl|spider|slurp|headless|preview|scan|curl|wget|python|java/|okhttp|monitor|lighthouse|pagespeed|telegrambot|facebookexternalhit)';
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    -- Fail-closed: só entra quem traz sinais positivos do clique comprovado.
    if lower(coalesce(new.device_type,'')) not in ('mobile','desktop','tablet')
       or btrim(coalesce(new.user_agent,'')) = ''
       or coalesce(new.user_agent,'') ~* c_bot
       or lower(coalesce(new.metadata->>'is_bot','false')) in ('true','1','yes')
       or lower(coalesce(new.metadata->>'proved_human','false')) not in ('true','1','yes')
       or coalesce(new.metadata->>'proof','') <> 'interstitial_beacon' then
      return new;
    end if;
    perform public.nexus_v420_enqueue(
      'public.ads_clicks', new.id::text, 'grupo_cliques',
      jsonb_build_object(
        'source','public.ads_clicks','click_id',new.id::text,
        'site',new.site_slug,'slot',new.slot,'advertiser',new.advertiser,
        'network',new.network,'country',new.country,'device',new.device_type,
        'created_at',new.created_at,'metadata',new.metadata
      )
    );
  exception when others then
    perform public.nexus_v420_sintonizado('v420-click-trigger','grupo_cliques',
      sqlstate || ': ' || left(sqlerrm,300));
  end;
  return new;
end;
$function$;

drop trigger if exists trg_v420_ads_click_channel on public.ads_clicks;
create trigger trg_v420_ads_click_channel
after insert on public.ads_clicks
for each row execute function public.nexus_v420_ads_click_enqueue();

create or replace function public.nexus_v420_nostr_enqueue()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    perform public.nexus_v420_enqueue(
      'public.nexus_v385_nostr_mentions', new.id::text, 'atendimento',
      jsonb_build_object(
        'source','public.nexus_v385_nostr_mentions','mention_id',new.id,
        'nostr_id',new.nostr_id,'relay_url',new.relay_url,'autor',new.autor,
        'texto',new.texto,'keyword',new.keyword,'node_origem',new.node_origem,
        'recebido_em',new.recebido_em
      )
    );
  exception when others then
    perform public.nexus_v420_sintonizado('v420-nostr-trigger','atendimento',
      sqlstate || ': ' || left(sqlerrm,300));
  end;
  return new;
end;
$function$;

-- A ponte v390 disparava composição HTTP unitária por menção; v420 preserva o
-- texto cru e consolida exclusivamente pelo outbox da rota atendimento.
drop trigger if exists trg_v390_mention_bridge on public.nexus_v385_nostr_mentions;
drop trigger if exists trg_v420_nostr_channel on public.nexus_v385_nostr_mentions;
create trigger trg_v420_nostr_channel
after insert on public.nexus_v385_nostr_mentions
for each row execute function public.nexus_v420_nostr_enqueue();

create or replace function public.nexus_v420_conversion_enqueue()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_status text;
  v_amount numeric;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    v_status := lower(btrim(coalesce(nullif(new.raw->>'transaction_status',''),new.status,'')));
    v_amount := coalesce(new.commission_amount,0);
    -- Silêncio absoluto para delta zero, pendência, reversão ou status desconhecido.
    if v_amount <= 0 or v_status not in
       ('approved','confirmed','validated','locked','paid','completed') then
      return new;
    end if;
    perform public.nexus_v420_enqueue(
      'public.affiliate_conversions', new.id::text, 'vendas_real',
      jsonb_build_object(
        'source','public.affiliate_conversions','conversion_id',new.id,
        'network',new.network,'external_id',new.external_id,
        'advertiser',new.advertiser,'order_id',new.order_id,
        'country',new.country,'status',v_status,'action_type',new.action_type,
        'commission_amount',v_amount,
        'commission_currency',coalesce(nullif(new.commission_currency,''),nullif(new.currency,''),'N/D'),
        'action_date',new.action_date,'validated_at',coalesce(new.validation_date,new.updated_at)
      )
    );
  exception when others then
    perform public.nexus_v420_sintonizado('v420-conversion-trigger','vendas_real',
      sqlstate || ': ' || left(sqlerrm,300));
  end;
  return new;
end;
$function$;

-- O trigger anterior enviava uma mensagem unitária por INSERT/UPDATE.
drop trigger if exists trg_telegram_real_sale on public.affiliate_conversions;
drop trigger if exists trg_v420_conversion_channel on public.affiliate_conversions;
create trigger trg_v420_conversion_channel
after insert or update of status, raw, commission_amount, commission_currency
on public.affiliate_conversions
for each row execute function public.nexus_v420_conversion_enqueue();

create or replace function public.nexus_v420_offer_enqueue_trigger()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    perform public.nexus_v420_enqueue(
      'public.nexus_telegram_c2_ofertas', new.id::text, 'ofertas',
      jsonb_build_object(
        'source','public.nexus_telegram_c2_ofertas','offer_row_id',new.id,
        'source_key',new.source_key,'offer_id',new.offer_id,'titulo',new.titulo,
        'loja',new.loja,'preco_brl',new.preco_brl,'preco_de_brl',new.preco_de_brl,
        'cupom',new.cupom,'click_url',new.click_url,'action_url',new.action_url,
        'button_text',new.button_text,'metadata',new.metadata,'criado_em',new.criado_em
      )
    );
  exception when others then
    perform public.nexus_v420_sintonizado('v420-offer-trigger','ofertas',
      sqlstate || ': ' || left(sqlerrm,300));
  end;
  return new;
end;
$function$;

drop trigger if exists trg_v420_offer_channel on public.nexus_telegram_c2_ofertas;
create trigger trg_v420_offer_channel
after insert on public.nexus_telegram_c2_ofertas
for each row execute function public.nexus_v420_offer_enqueue_trigger();

-- -----------------------------------------------------------------------------
-- 6. Entrada RPC de ofertas. Recebe apenas preço BRL positivo + link HTTPS.
-- O action_url usa o shortener Cloudflare; dest64 preserva o fallback específico.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_v420_offer_enqueue(p_offer jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_id bigint;
  v_price numeric;
  v_old numeric;
  v_click text;
  v_action text;
  v_key text;
  v_dest64 text;
  v_brand text;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    if p_offer is null or jsonb_typeof(p_offer) <> 'object' then
      return jsonb_build_object('ok',false,'motivo','payload_invalido');
    end if;
    if btrim(coalesce(p_offer->>'title','')) = '' then
      return jsonb_build_object('ok',false,'motivo','titulo_invalido');
    end if;
    v_price := replace(coalesce(p_offer->>'price_brl',''),',','.')::numeric;
    if v_price <= 0 then
      return jsonb_build_object('ok',false,'motivo','preco_brl_invalido');
    end if;
    begin
      v_old := nullif(replace(coalesce(p_offer->>'original_price_brl',''),',','.'),'')::numeric;
    exception when others then v_old := null;
    end;
    if v_old is not null and v_old <= v_price then v_old := null; end if;
    v_click := btrim(coalesce(p_offer->>'click_url',''));
    if v_click !~* '^https://[^[:space:]]+$' then
      return jsonb_build_object('ok',false,'motivo','click_url_invalido');
    end if;
    v_key := left(coalesce(nullif(btrim(p_offer->>'source_key'),''),
                    md5(v_click || '|' || coalesce(p_offer->>'title',''))),200);
    v_brand := left(lower(regexp_replace(coalesce(p_offer->>'brand','auto'),'[^a-z0-9_]','','g')),40);
    if v_brand = '' then v_brand := 'auto'; end if;
    v_dest64 := replace(translate(replace(encode(convert_to(v_click,'UTF8'),'base64'),E'\n',''),'+/','-_'),'=','');
    v_action := 'https://www.aquitemachadinhos.com.br/go?marca=' || v_brand ||
                '&dest64=' || v_dest64 || '&sid=tg_ofertas_v420_' ||
                left(regexp_replace(v_key,'[^a-zA-Z0-9]','','g'),32);

    insert into public.nexus_telegram_c2_ofertas
      (source_key,offer_id,titulo,loja,preco_brl,preco_de_brl,cupom,
       click_url,action_url,button_text,metadata)
    values
      (v_key,left(p_offer->>'offer_id',120),left(btrim(p_offer->>'title'),180),
       left(p_offer->>'merchant',100),v_price,v_old,left(p_offer->>'coupon',80),
       v_click,v_action,left(coalesce(nullif(p_offer->>'button_text',''),'Ver oferta'),48),
       coalesce(p_offer->'metadata','{}'::jsonb))
    on conflict (source_key) do nothing
    returning id into v_id;

    if v_id is null then
      return jsonb_build_object('ok',true,'queued',false,'motivo','duplicado_contido');
    end if;
    return jsonb_build_object('ok',true,'queued',true,'id',v_id);
  exception when others then
    perform public.nexus_v420_sintonizado('v420-offer-rpc','ofertas',
      sqlstate || ': ' || left(sqlerrm,300));
    return jsonb_build_object('ok',false,'motivo','Sintonizado em Análise');
  end;
end;
$function$;
revoke all on function public.nexus_v420_offer_enqueue(jsonb) from public, anon, authenticated;
grant execute on function public.nexus_v420_offer_enqueue(jsonb) to service_role;

-- -----------------------------------------------------------------------------
-- 7. Layouts consolidados. Toda interpolação textual passa por HTML escape.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_v420_layout_clicks(p_rows jsonb)
returns text
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_n int := coalesce(jsonb_array_length(p_rows),0);
  v_geo text;
  v_sites text;
  v_networks text;
  v_lines text;
  v_sb int; v_pop int; v_mon int; v_hosts int;
  v_display numeric;
  v_display_line text;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    select string_agg(public.nexus_v420_html_escape(k) || '×' || n, ' · ' order by n desc,k)
      into v_geo from (
        select coalesce(nullif(e->>'country',''),'??') k,count(*) n
        from jsonb_array_elements(p_rows) e group by 1
      ) s;
    select string_agg(public.nexus_v420_html_escape(k) || '×' || n, ' · ' order by n desc,k)
      into v_sites from (
        select coalesce(nullif(e->>'site',''),'origem não informada') k,count(*) n
        from jsonb_array_elements(p_rows) e group by 1
      ) s;
    select string_agg(public.nexus_v420_html_escape(k) || '×' || n, ' · ' order by n desc,k)
      into v_networks from (
        select coalesce(nullif(e->>'network',''),'não informada') k,count(*) n
        from jsonb_array_elements(p_rows) e group by 1
      ) s;
    select string_agg('• ' || public.nexus_v420_html_escape(coalesce(nullif(e->>'advertiser',''),nullif(e->>'slot',''),'clique')) ||
                      ' · ' || public.nexus_v420_html_escape(coalesce(e->>'country','??')) ||
                      ' · ' || public.nexus_v420_html_escape(coalesce(e->>'device','?')), chr(10))
      into v_lines from (select value e from jsonb_array_elements(p_rows) limit 12) q;

    select count(*) filter (where socialbar_url is not null),
           count(*) filter (where popunder_url is not null),
           count(*) filter (where monetag_loader is not null),
           count(*)
      into v_sb,v_pop,v_mon,v_hosts
      from public.nexus_host_tag_alignment where is_active;

    select sum((e->'metadata'->>'display_revenue_usd')::numeric)
      into v_display
      from jsonb_array_elements(p_rows) e
     where coalesce(e->'metadata'->>'display_revenue_usd','') ~ '^[0-9]+([.][0-9]+)?$';
    v_display_line := case when v_display is null
      then 'não informado nos eventos — nenhum valor foi estimado'
      else 'US$ ' || to_char(v_display,'FM999999990D0000') end;

    return '📊 <b>NEXUS LEDGER — LOTE DE CLIQUES HUMANOS CONSOLIDADO</b>' || chr(10) ||
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━' || chr(10) ||
      '⏱ ' || to_char(now() at time zone 'America/Sao_Paulo','DD/MM/YYYY HH24:MI:SS') || ' SP' || chr(10) ||
      '🖱 <b>' || v_n || '</b> clique(s) comprovado(s)' || chr(10) ||
      '🌎 ' || coalesce(v_geo,'sem país medido') || chr(10) ||
      '🏛 ' || coalesce(v_sites,'sem origem medida') || chr(10) ||
      '🔗 ' || coalesce(v_networks,'sem rede medida') || chr(10) || chr(10) ||
      '💵 <b>GANHOS DE DISPLAY — MEDIÇÃO DO LOTE</b>' || chr(10) ||
      '• Receita informada: ' || v_display_line || chr(10) ||
      '• Bindings ativos: Adsterra sb=' || coalesce(v_sb,0) || '/' || coalesce(v_hosts,0) ||
      '; pop=' || coalesce(v_pop,0) || '/' || coalesce(v_hosts,0) ||
      ' · Monetag=' || coalesce(v_mon,0) || '/' || coalesce(v_hosts,0) || chr(10) || chr(10) ||
      coalesce(v_lines,'• sem detalhe adicional') || chr(10) ||
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━' || chr(10) ||
      '<i>Fonte exclusiva: public.ads_clicks · lote v420.0</i>';
  exception when others then
    perform public.nexus_v420_sintonizado('v420-layout-clicks','grupo_cliques',sqlerrm);
    return '📊 <b>NEXUS LEDGER</b>' || chr(10) || 'Sintonizado em Análise';
  end;
end;
$function$;

create or replace function public.nexus_v420_layout_capture(p_rows jsonb)
returns text
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_n int := coalesce(jsonb_array_length(p_rows),0);
  v_lines text;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    select string_agg(
      '🔎 <b>Keyword:</b> <code>' || public.nexus_v420_html_escape(coalesce(e->>'keyword','não informada')) || '</code>' || chr(10) ||
      '👤 <b>Autor:</b> <code>' || public.nexus_v420_html_escape(left(coalesce(e->>'autor','não informado'),80)) || '</code>' || chr(10) ||
      '🛰 <b>Nó/relay:</b> ' || public.nexus_v420_html_escape(left(coalesce(e->>'node_origem','?'),20)) ||
      ' · ' || public.nexus_v420_html_escape(left(coalesce(e->>'relay_url','?'),100)) || chr(10) ||
      '📝 <b>Texto cru capturado:</b>' || chr(10) || '<pre>' ||
      public.nexus_v420_html_escape(left(coalesce(e->>'texto',''),520)) || '</pre>',
      chr(10) || '────────────────────────' || chr(10)
    ) into v_lines
    from (select value e from jsonb_array_elements(p_rows) limit 6) q;

    return '📡 <b>SENTINEL NEXUS — CAPTURA CONSOLIDADA</b>' || chr(10) ||
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━' || chr(10) ||
      '⏱ ' || to_char(now() at time zone 'America/Sao_Paulo','DD/MM/YYYY HH24:MI:SS') || ' SP' || chr(10) ||
      '🧠 Aho-Corasick · RAM · ' || v_n || ' menção(ões)' || chr(10) || chr(10) ||
      coalesce(v_lines,'<i>sem menção no lote</i>') || chr(10) ||
      '<i>Fonte exclusiva: public.nexus_v385_nostr_mentions · lote v420.0</i>';
  exception when others then
    perform public.nexus_v420_sintonizado('v420-layout-capture','atendimento',sqlerrm);
    return '📡 <b>SENTINEL NEXUS</b>' || chr(10) || 'Sintonizado em Análise';
  end;
end;
$function$;

create or replace function public.nexus_v420_layout_sales(p_rows jsonb)
returns text
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_n int := coalesce(jsonb_array_length(p_rows),0);
  v_delta numeric;
  v_lines text;
  v_totals text;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    select coalesce(sum((e->>'commission_amount')::numeric),0)
      into v_delta from jsonb_array_elements(p_rows) e
     where coalesce(e->>'commission_amount','') ~ '^[0-9]+([.][0-9]+)?$';
    if v_n = 0 or v_delta <= 0 then
      return null; -- silêncio absoluto; o flush descarta sem chamar Telegram
    end if;
    select string_agg(
      '• ' || public.nexus_v420_html_escape(coalesce(nullif(e->>'network',''),'rede não informada')) ||
      ' · ' || public.nexus_v420_html_escape(coalesce(nullif(e->>'advertiser',''),'varejo/Booking')) ||
      ' · <b>' || to_char((e->>'commission_amount')::numeric,'FM999999990D00') || ' ' ||
      public.nexus_v420_html_escape(coalesce(e->>'commission_currency','N/D')) || '</b>' ||
      ' · ' || public.nexus_v420_html_escape(coalesce(e->>'status','confirmada')), chr(10))
      into v_lines from (select value e from jsonb_array_elements(p_rows) limit 12) q;
    select string_agg('• <b>' || to_char(total,'FM999999990D00') || ' ' ||
                      public.nexus_v420_html_escape(currency) || '</b>', chr(10) order by currency)
      into v_totals from (
        select coalesce(e->>'commission_currency','N/D') currency,
               sum((e->>'commission_amount')::numeric) total
        from jsonb_array_elements(p_rows) e
        where coalesce(e->>'commission_amount','') ~ '^[0-9]+([.][0-9]+)?$'
        group by 1
      ) s;

    return '💰 <b>NEXUS LEDGER — FECHAMENTO DE CAIXA CONFIRMADO</b>' || chr(10) ||
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━' || chr(10) ||
      '⏱ ' || to_char(now() at time zone 'America/Sao_Paulo','DD/MM/YYYY HH24:MI:SS') || ' SP' || chr(10) ||
      '✅ ' || v_n || ' conversão(ões) com comissão positiva e status confirmado' || chr(10) || chr(10) ||
      coalesce(v_lines,'') || chr(10) || chr(10) ||
      '<b>TOTAIS POR MOEDA — sem conversão cambial inventada</b>' || chr(10) ||
      coalesce(v_totals,'') || chr(10) ||
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━' || chr(10) ||
      '<i>Fonte exclusiva: public.affiliate_conversions · lote v420.0</i>';
  exception when others then
    perform public.nexus_v420_sintonizado('v420-layout-sales','vendas_real',sqlerrm);
    return null;
  end;
end;
$function$;

create or replace function public.nexus_v420_layout_offers(p_rows jsonb)
returns text
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_n int := coalesce(jsonb_array_length(p_rows),0);
  v_lines text;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    select string_agg(
      '🛍 <b>' || public.nexus_v420_html_escape(left(coalesce(e->>'titulo','Oferta'),150)) || '</b>' || chr(10) ||
      case when nullif(e->>'loja','') is not null
           then '🏪 ' || public.nexus_v420_html_escape(e->>'loja') || chr(10) else '' end ||
      case when nullif(e->>'preco_de_brl','') is not null
           then 'De <s>R$ ' || replace(to_char((e->>'preco_de_brl')::numeric,'FM999999990D00'),'.',',') || '</s> · ' else '' end ||
      '<b>R$ ' || replace(to_char((e->>'preco_brl')::numeric,'FM999999990D00'),'.',',') || '</b>' ||
      case when nullif(e->>'cupom','') is not null
           then chr(10) || '🎟 Cupom: <code>' || public.nexus_v420_html_escape(e->>'cupom') || '</code>' else '' end,
      chr(10) || chr(10)
    ) into v_lines
    from (select value e from jsonb_array_elements(p_rows) limit 8) q;

    return '✨ <b>OFERTAS BRASIL — SELEÇÃO VERIFICADA</b>' || chr(10) ||
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━' || chr(10) ||
      coalesce(v_lines,'') || chr(10) ||
      'Os preços acima são os valores recebidos do catálogo; confirme estoque e frete na loja.' || chr(10) || chr(10) ||
      '#publi' || chr(10) ||
      '<b>Use os botões abaixo para abrir cada oferta.</b>';
  exception when others then
    perform public.nexus_v420_sintonizado('v420-layout-offers','ofertas',sqlerrm);
    return null;
  end;
end;
$function$;

create or replace function public.nexus_v420_offer_buttons(p_rows jsonb)
returns jsonb
language sql
stable
set search_path to 'public', 'pg_temp'
as $function$
  select jsonb_build_object('inline_keyboard',coalesce(jsonb_agg(
    jsonb_build_array(jsonb_build_object(
      'text',left(coalesce(nullif(e->>'button_text',''),'Ver oferta'),48),
      'url',e->>'action_url'
    )) order by ord),'[]'::jsonb))
  from jsonb_array_elements(coalesce(p_rows,'[]'::jsonb)) with ordinality q(e,ord)
  where ord <= 8 and coalesce(e->>'action_url','') ~* '^https://';
$function$;

-- -----------------------------------------------------------------------------
-- 8. Reconciliador assíncrono pg_net. Falha é terminal e não gera reenvio.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_v420_reconcile(p_limit integer default 40)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'net', 'pg_temp'
as $function$
declare
  r record;
  v_res jsonb;
  v_http integer;
  v_ok boolean;
  v_body text;
  v_done integer := 0;
  v_fail integer := 0;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    for r in
      select id,request_id,channel_key from public.nexus_v420_dispatch_log
       where reconciled_at is null order by id limit greatest(1,least(coalesce(p_limit,40),100))
       for update skip locked
    loop
      begin
        v_res := null;
        select to_jsonb(x) into v_res from net._http_response x where x.id=r.request_id;
        if v_res is null then continue; end if;
        v_http := coalesce((v_res->>'status_code')::integer,0);
        v_body := coalesce(v_res->>'content','');
        begin
          v_ok := v_http=200 and coalesce((v_body::jsonb->>'ok')::boolean,false);
        exception when others then v_ok := false;
        end;
        update public.nexus_v420_dispatch_log
           set reconciled_at=now(),http_status=v_http,telegram_ok=v_ok,
               response_preview=left(v_body,300)
         where id=r.id;
        update public.nexus_v420_event_registry
           set state=case when v_ok then 'delivered' else 'failed' end,
               finalized_at=now()
         where request_id=r.request_id;
        delete from net._http_response where id=r.request_id;
        v_done := v_done+1;
        if not v_ok then
          v_fail := v_fail+1;
          perform public.nexus_v420_sintonizado('v420-telegram-network',r.channel_key,
            'Sintonizado em Análise · request_id='||r.request_id||' · HTTP '||v_http);
        end if;
      exception when others then
        perform public.nexus_v420_sintonizado('v420-reconcile',r.channel_key,
          sqlstate || ': ' || left(sqlerrm,260));
      end;
    end loop;
    return jsonb_build_object('reconciliados',v_done,'falhas',v_fail);
  exception when others then
    perform public.nexus_v420_sintonizado('v420-reconcile',null,
      sqlstate || ': ' || left(sqlerrm,260));
    return jsonb_build_object('sintonizado',true,'motivo','Sintonizado em Análise');
  end;
end;
$function$;

-- -----------------------------------------------------------------------------
-- 9. Flush mestre: uma mensagem consolidada por canal/ciclo.
-- Submissão ao pg_net, recibo e DELETE da fila são uma única subtransação.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_v420_flush_10s(p_block integer default 40)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions', 'net', 'pg_temp'
as $function$
declare
  r_route record;
  v_token text;
  v_enabled text;
  v_ids bigint[];
  v_registry_ids bigint[];
  v_pks text[];
  v_rows jsonb;
  v_n integer;
  v_limit integer;
  v_text text;
  v_body jsonb;
  v_req bigint;
  v_deleted integer;
  v_results jsonb := '[]'::jsonb;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    if not pg_try_advisory_xact_lock(hashtext('nexus-v420-flush')) then
      return jsonb_build_object('idle',true,'motivo','outro flush possui o lock');
    end if;
    perform public.nexus_v420_reconcile(40);
    select value into v_enabled from public.nexus_growth_secrets where key='telegram_alerts_enabled';
    if coalesce(v_enabled,'false') <> 'true' then
      return jsonb_build_object('idle',true,'motivo','kill-switch telegram_alerts_enabled=false');
    end if;
    select value into v_token from public.nexus_growth_secrets where key='telegram_bot_token';
    if coalesce(btrim(v_token),'') = '' then
      perform public.nexus_v420_sintonizado('v420-flush',null,'telegram_bot_token ausente');
      return jsonb_build_object('sintonizado',true,'motivo','Sintonizado em Análise');
    end if;

    for r_route in
      select * from public.nexus_v420_channel_routes where enabled order by channel_key
    loop
      begin
        v_limit := case r_route.channel_key when 'atendimento' then 6 when 'ofertas' then 8
                     when 'vendas_real' then 12 else least(greatest(coalesce(p_block,40),1),40) end;
        select array_agg(id order by id),array_agg(registry_id order by id),
               array_agg(source_pk order by id),jsonb_agg(payload order by id)
          into v_ids,v_registry_ids,v_pks,v_rows
          from (
            select id,registry_id,source_pk,payload
              from public.nexus_v420_channel_outbox
             where channel_key=r_route.channel_key
               and source_relation=r_route.source_relation
             order by id limit v_limit
             for update skip locked
          ) q;
        v_n := coalesce(array_length(v_ids,1),0);
        if v_n=0 then continue; end if;

        v_text := case r_route.layout_key
          when 'clicks_ledger' then public.nexus_v420_layout_clicks(v_rows)
          when 'sentinel_capture' then public.nexus_v420_layout_capture(v_rows)
          when 'cash_close' then public.nexus_v420_layout_sales(v_rows)
          when 'offer_buttons' then public.nexus_v420_layout_offers(v_rows)
          else null end;

        if v_text is null or btrim(v_text)='' then
          update public.nexus_v420_event_registry
             set state='dropped',finalized_at=now()
           where registry_id=any(v_registry_ids);
          delete from public.nexus_v420_channel_outbox where id=any(v_ids);
          v_results := v_results || jsonb_build_array(jsonb_build_object(
            'canal',r_route.channel_key,'eventos',v_n,'enviado',false,'motivo','delta_zero_ou_layout_fechado'));
          continue;
        end if;

        v_body := jsonb_build_object(
          'chat_id',r_route.chat_id,'text',left(v_text,4000),
          'parse_mode','HTML','link_preview_options',jsonb_build_object('is_disabled',true)
        );
        if r_route.layout_key='offer_buttons' then
          v_body := v_body || jsonb_build_object('reply_markup',public.nexus_v420_offer_buttons(v_rows));
        end if;

        select net.http_post(
          url:='https://api.telegram.org/bot'||v_token||'/sendMessage',
          headers:='{"Content-Type":"application/json"}'::jsonb,
          body:=v_body,
          timeout_milliseconds:=1000
        ) into v_req;
        if v_req is null then raise exception 'pg_net não devolveu request_id'; end if;

        insert into public.nexus_v420_dispatch_log
          (request_id,channel_key,chat_id,source_relation,source_pks,event_count,body_sha256)
        values
          (v_req,r_route.channel_key,r_route.chat_id,r_route.source_relation,v_pks,v_n,
           encode(extensions.digest(v_text,'sha256'),'hex'));

        update public.nexus_v420_event_registry
           set state='submitted',request_id=v_req,submitted_at=now()
         where registry_id=any(v_registry_ids);

        -- Limpeza imediatamente depois da submissão. Se qualquer comando acima/abaixo
        -- falhar, o bloco EXCEPTION desfaz também a solicitação pg_net.
        delete from public.nexus_v420_channel_outbox where id=any(v_ids);
        get diagnostics v_deleted=row_count;
        if v_deleted<>v_n then raise exception 'flush parcial: esperado %, apagado %',v_n,v_deleted; end if;

        v_results := v_results || jsonb_build_array(jsonb_build_object(
          'canal',r_route.channel_key,'chat_id',r_route.chat_id,'eventos',v_n,
          'enviado',true,'request_id',v_req,'fila_limpa',v_deleted));
      exception when others then
        perform public.nexus_v420_sintonizado('v420-flush',r_route.channel_key,
          sqlstate || ': ' || left(sqlerrm,260));
        v_results := v_results || jsonb_build_array(jsonb_build_object(
          'canal',r_route.channel_key,'enviado',false,'motivo','Sintonizado em Análise'));
      end;
    end loop;
    return jsonb_build_object('versao','v420.0','resultados',v_results,'aferido_em',now());
  exception when others then
    perform public.nexus_v420_sintonizado('v420-flush',null,
      sqlstate || ': ' || left(sqlerrm,260));
    return jsonb_build_object('sintonizado',true,'motivo','Sintonizado em Análise');
  end;
end;
$function$;

-- Compatibilidade do Job 60 e de chamadores antigos: nenhum classificador legado roda.
create or replace function public.nexus_v360_flush_10s(p_block integer default 18)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    return public.nexus_v420_flush_10s(greatest(1,least(coalesce(p_block,18),40)));
  exception when others then
    perform public.nexus_v420_sintonizado('v360-tg-flush-10s','job-60',
      'Sintonizado em Análise · '||sqlstate||': '||left(sqlerrm,240));
    return jsonb_build_object('sintonizado',true,'motivo','Sintonizado em Análise');
  end;
end;
$function$;

-- -----------------------------------------------------------------------------
-- 10. C2 diário passa a materializar fatos na tabela C2; não envia diretamente.
-- Só usa preço BRL positivo, link HTTPS e atualização <=7 dias.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_telegram_ofertas_broadcast()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  r record;
  v_n integer:=0;
  v_dest64 text;
  v_action text;
  v_key text;
begin
  perform set_config('statement_timeout','2000',true);
  perform set_config('lock_timeout','1000',true);
  begin
    for r in
      select id,titulo,preco_atual,preco_de,desconto_pct,loja_origem,link_afiliado,meta_dados
        from public.produtos_ofertas
       where ativo is true and upper(coalesce(moeda,''))='BRL'
         and preco_atual>0 and link_afiliado~*'^https://[^[:space:]]+$'
         and atualizado_em>=now()-interval '7 days'
       order by atualizado_em desc,desconto_pct desc nulls last
       limit 4
    loop
      v_key:='catalog:'||r.id||':'||to_char(current_date,'YYYYMMDD');
      v_dest64:=replace(translate(replace(encode(convert_to(r.link_afiliado,'UTF8'),'base64'),E'\n',''),'+/','-_'),'=','');
      v_action:='https://www.aquitemachadinhos.com.br/go?marca=auto&dest64='||v_dest64||
                '&sid=tg_ofertas_v420_'||left(regexp_replace(r.id,'[^a-zA-Z0-9]','','g'),28);
      insert into public.nexus_telegram_c2_ofertas
        (source_key,offer_id,titulo,loja,preco_brl,preco_de_brl,click_url,action_url,button_text,metadata)
      values
        (v_key,r.id,left(r.titulo,180),left(r.loja_origem,100),r.preco_atual,r.preco_de,
         r.link_afiliado,v_action,'Ver oferta',coalesce(r.meta_dados,'{}'::jsonb))
      on conflict(source_key) do nothing;
      if found then v_n:=v_n+1; end if;
    end loop;
    return case when v_n=0
      then jsonb_build_object('ok',true,'silencio',true,'motivo','nenhuma oferta BRL fresca e inédita')
      else jsonb_build_object('ok',true,'enfileiradas',v_n,'destino','-1004317377063') end;
  exception when others then
    perform public.nexus_v420_sintonizado('v420-c2-materialize','ofertas',
      sqlstate||': '||left(sqlerrm,260));
    return jsonb_build_object('ok',false,'motivo','Sintonizado em Análise');
  end;
end;
$function$;

-- -----------------------------------------------------------------------------
-- 11. Desativa o buffer/fan-out legado sem propagar erro para os produtores.
-- Toda inserção antiga é descartada fail-closed; os 32 itens já despachados da
-- auditoria são removidos. A tabela de eventos/catálogo não é truncada.
-- -----------------------------------------------------------------------------
create or replace function public.nexus_v420_legacy_buffer_closed()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  return null;
end;
$function$;

drop trigger if exists trg_v420_legacy_buffer_closed on public.nexus_telegram_message_buffer;
create trigger trg_v420_legacy_buffer_closed
before insert on public.nexus_telegram_message_buffer
for each row execute function public.nexus_v420_legacy_buffer_closed();
truncate table public.nexus_telegram_message_buffer;
revoke all on table public.nexus_telegram_message_buffer from anon,authenticated,service_role;
revoke all on sequence public.nexus_telegram_message_buffer_id_seq from anon,authenticated,service_role;
-- Portas legadas SECURITY DEFINER deixam de ser chamáveis via PostgREST. Os
-- owners dos jobs/triggers ainda podem executá-las quando necessário fora deste
-- pipeline, mas elas não podem disputar o Job 60 nem contornar o mapa v420.
revoke all on function public.nexus_telegram_flush_consume(),
                       public.nexus_telegram_flush_dispatch(),
                       public.nexus_telegram_flush_pulse(),
                       public.nexus_v375_tg_flush_safe(),
                       public.nexus_v360_flush_10s(integer),
                       public.nexus_telegram_ofertas_broadcast(),
                       public.nexus_telegram_push(text,text,text),
                       public.nexus_telegram_send_to(text,text,text,text)
  from public,anon,authenticated,service_role;

-- Job 60 mantém o nome/ID operacional, mas executa apenas o mestre v420.
do $block$
declare v_job bigint;
begin
  select jobid into v_job from cron.job where jobname='v360-tg-flush-10s';
  if v_job is null then
    perform cron.schedule('v360-tg-flush-10s','10 seconds','select public.nexus_v420_flush_10s();');
  else
    perform cron.alter_job(job_id:=v_job,schedule:='10 seconds',
                           command:='select public.nexus_v420_flush_10s();',active:=true);
  end if;
exception when others then
  perform public.nexus_v420_sintonizado('v420-cron','job-60',
    sqlstate||': '||left(sqlerrm,260));
end;
$block$;

-- -----------------------------------------------------------------------------
-- 12. Views executivas de prova; sem exposição pública.
-- -----------------------------------------------------------------------------
create or replace view public.nexus_v420_channel_map_v as
select r.source_relation,
       to_regclass(r.source_relation) is not null as source_exists,
       r.channel_key,r.chat_id,r.channel_title,r.layout_key,r.enabled,r.verified_at,
       coalesce(q.queued,0) as queued,
       d.last_submitted_at,d.last_telegram_ok
from public.nexus_v420_channel_routes r
left join (
  select source_relation,channel_key,count(*) queued
  from public.nexus_v420_channel_outbox group by 1,2
) q using(source_relation,channel_key)
left join lateral (
  select submitted_at last_submitted_at,telegram_ok last_telegram_ok
  from public.nexus_v420_dispatch_log l
  where l.source_relation=r.source_relation and l.channel_key=r.channel_key
  order by id desc limit 1
) d on true
order by r.channel_key;

create or replace view public.nexus_v420_status_v as
select
  'v420.0'::text as version,
  (select count(*) from public.nexus_v420_channel_routes where enabled) as routes_enabled,
  (select count(distinct source_relation) from public.nexus_v420_channel_routes where enabled) as sources_unique,
  (select count(distinct channel_key) from public.nexus_v420_channel_routes where enabled) as channels_unique,
  (select count(distinct chat_id) from public.nexus_v420_channel_routes where enabled) as chats_unique,
  (select count(*) from public.nexus_v420_channel_outbox) as queue_depth,
  (select count(*) from public.nexus_telegram_message_buffer) as legacy_queue_depth,
  (select count(*) from public.ads where active is true) as active_ads_read_only,
  (select count(*) from public.nexus_v360_node_endpoints where ativo) as satellite_nodes_active,
  (select count(distinct project_ref) from public.nexus_v360_node_endpoints where ativo) as satellite_project_refs_unique,
  (select active from cron.job where jobname='v360-tg-flush-10s' limit 1) as job_60_active,
  (select command from cron.job where jobname='v360-tg-flush-10s' limit 1) as job_60_command,
  now() as checked_at;

revoke all on table public.nexus_v420_channel_map_v,public.nexus_v420_status_v
  from anon,authenticated,service_role;
grant select on table public.nexus_v420_channel_map_v,public.nexus_v420_status_v to service_role;

-- Funções internas não ficam executáveis pelos papéis públicos do PostgREST.
revoke all on function public.nexus_v420_enqueue(text,text,text,jsonb),
                       public.nexus_v420_ads_click_enqueue(),
                       public.nexus_v420_nostr_enqueue(),
                       public.nexus_v420_conversion_enqueue(),
                       public.nexus_v420_offer_enqueue_trigger(),
                       public.nexus_v420_layout_clicks(jsonb),
                       public.nexus_v420_layout_capture(jsonb),
                       public.nexus_v420_layout_sales(jsonb),
                       public.nexus_v420_layout_offers(jsonb),
                       public.nexus_v420_offer_buttons(jsonb),
                       public.nexus_v420_reconcile(integer),
                       public.nexus_v420_flush_10s(integer),
                       public.nexus_v420_sintonizado(text,text,text),
                       public.nexus_v420_legacy_buffer_closed()
  from public,anon,authenticated,service_role;
-- Única porta escrita externa: oferta validada; flush continua exclusivo do owner/cron.
grant execute on function public.nexus_v420_offer_enqueue(jsonb) to service_role;

-- Asserts finais: qualquer divergência cancela TODA a migração.
do $verify$
declare
  v_before record;
  v_after record;
  v_routes integer;
begin
  select * into v_before from nexus_v420_catalog_guard;
  select count(*)::bigint total,count(*) filter(where active is true)::bigint ativos
    into v_after from public.ads;
  if v_before.total<>v_after.total or v_before.ativos<>v_after.ativos then
    raise exception 'v420 abortada: catálogo mudou (%/% -> %/%)',
      v_before.total,v_before.ativos,v_after.total,v_after.ativos;
  end if;
  select count(*) into v_routes from public.nexus_v420_channel_routes where enabled;
  if v_routes<>4
     or (select count(distinct source_relation) from public.nexus_v420_channel_routes where enabled)<>4
     or (select count(distinct channel_key) from public.nexus_v420_channel_routes where enabled)<>4
     or (select count(distinct chat_id) from public.nexus_v420_channel_routes where enabled)<>4 then
    raise exception 'v420 abortada: mapa não é 1:1 (rotas=%)',v_routes;
  end if;
  if exists(select 1 from public.nexus_v420_channel_routes where to_regclass(source_relation) is null) then
    raise exception 'v420 abortada: fonte registrada não existe';
  end if;
  if (select count(*) from public.nexus_v360_node_endpoints where ativo)<>13
     or (select count(distinct project_ref) from public.nexus_v360_node_endpoints where ativo)<>13 then
    raise exception 'v420 abortada: frota analítica não contém 13 satélites 1:1';
  end if;
end;
$verify$;

commit;

select * from public.nexus_v420_status_v;
select * from public.nexus_v420_channel_map_v;
